"use client";
import {useMemo,useState} from "react";
import {createBrowserClient} from "@supabase/ssr";

type Row={user_id:string;email:string;signup_at:string;last_sign_in_at:string|null;jobs:any[];interviews:any[];tasks:any[];documents:any[]};
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}):"Never";
type Analytics={total_signups:number;tour_completed:number;first_job_added:number;person_added:number;task_added:number;interview_added:number;find_jobs_used:number;returned_another_day:number;active_7d:number;new_7d:number};
type Attribution={source:string;campaign:string;signups:number;first_signup:string;last_signup:string};
type Deep={activation_rate:number;avg_jobs_per_user:number;users_0_jobs:number;users_1_job:number;users_2_5_jobs:number;users_6plus_jobs:number;people_users:number;task_users:number;interview_users:number;outreach_users:number;notes_users:number;total_jobs:number;applied_jobs:number;interview_jobs:number;offer_jobs:number;closed_jobs:number;tasks_completed:number;people_added:number;outreach_saved:number;feedback_total:number;retained_2plus_days:number};
type SourceQuality={source:string;campaign:string;signups:number;activated:number;retained:number;activation_rate:number};
type SubscriptionAnalytics={active_premium:number;active_trials:number;total_trials:number;total_paid_starts:number;trial_conversions:number;trial_conversion_rate:number;cancellations:number;avg_months_before_cancel:number;mrr_cents:number;complimentary:number;monthly:Array<{month_label:string;trials:number;paid:number;cancellations:number}>};
export default function JgoJobAdmin({initialUsers,initialAnalytics,initialAttribution,initialDeep,initialSourceQuality,initialSubscription}:{initialUsers:Row[];initialAnalytics:Analytics|null;initialAttribution:Attribution[];initialDeep:Deep|null;initialSourceQuality:SourceQuality[];initialSubscription:SubscriptionAnalytics|null}){
 const [q,setQ]=useState(""),[open,setOpen]=useState<string|null>(null),[downloading,setDownloading]=useState<string|null>(null),[copied,setCopied]=useState<string|null>(null);
 const users=useMemo(()=>initialUsers.filter(u=>u.email?.toLowerCase().includes(q.toLowerCase())||u.jobs?.some(j=>(j.company+" "+j.title).toLowerCase().includes(q.toLowerCase()))),[q,initialUsers]);
 const totalJobs=initialUsers.reduce((n,u)=>n+(u.jobs?.length||0),0), totalDocs=initialUsers.reduce((n,u)=>n+(u.documents?.length||0),0), totalInterviews=initialUsers.reduce((n,u)=>n+(u.interviews?.length||0),0);
 const launchLinks=[
  {id:"instagram-reel",channel:"Instagram Bio / Reel",use:"Use in your bio or launch Reel caption/link destination.",url:"https://jgojob.com/?utm_source=instagram&utm_medium=social&utm_campaign=jgojob_launch&utm_content=launch_reel"},
  {id:"instagram-story",channel:"Instagram Story",use:"Use for the Story link sticker.",url:"https://jgojob.com/?utm_source=instagram&utm_medium=social&utm_campaign=jgojob_launch&utm_content=launch_story"},
  {id:"tiktok",channel:"TikTok",use:"Use in the launch video profile/link destination.",url:"https://jgojob.com/?utm_source=tiktok&utm_medium=social&utm_campaign=jgojob_launch&utm_content=launch_video"},
  {id:"jgohire",channel:"JGO Hire Website",use:"Tracked homepage launch link already used on JGOHire.com.",url:"https://jgojob.com/?utm_source=jgohire&utm_medium=website&utm_campaign=jgojob_launch&utm_content=homepage"},
  {id:"direct",channel:"Direct / General",use:"Clean link for texts, DMs or anywhere you do not need source attribution.",url:"https://jgojob.com/"}
 ];
 async function copyLaunchLink(id:string,url:string){try{await navigator.clipboard.writeText(url);setCopied(id);window.setTimeout(()=>setCopied(x=>x===id?null:x),1800)}catch{window.prompt("Copy this link:",url)}}
 const funnel: Array<[string,number]> = initialAnalytics ? [["Signed up",initialAnalytics.total_signups],["Tour done",initialAnalytics.tour_completed],["First job",initialAnalytics.first_job_added],["Person",initialAnalytics.person_added],["Task",initialAnalytics.task_added],["Interview",initialAnalytics.interview_added],["Find Jobs",initialAnalytics.find_jobs_used],["Returned",initialAnalytics.returned_another_day]] : [];

 const userCount=initialUsers.length||1;
 const usersWithJobs=initialUsers.filter(u=>(u.jobs?.length||0)>0).length;
 const activationPct=Math.round(usersWithJobs/userCount*100);
 const avgJobs=(totalJobs/userCount).toFixed(1);
 const jobs0=initialUsers.filter(u=>!u.jobs?.length).length, jobs1=initialUsers.filter(u=>u.jobs?.length===1).length, jobs2to5=initialUsers.filter(u=>(u.jobs?.length||0)>=2&&(u.jobs?.length||0)<=5).length, jobs6plus=initialUsers.filter(u=>(u.jobs?.length||0)>=6).length;
 const usersWithInterviews=initialUsers.filter(u=>(u.interviews?.length||0)>0).length;
 const usersWithTasks=initialUsers.filter(u=>(u.tasks?.length||0)>0).length;
 const engagedUsers=initialUsers.filter(u=>Number((u.jobs?.length||0)>0)+Number((u.tasks?.length||0)>0)+Number((u.interviews?.length||0)>0)>=2).length;
 const appliedJobs=initialUsers.flatMap(u=>u.jobs||[]).filter(j=>["applied","follow_up","interview","final_interview","offer"].includes(j.status)).length;
 const interviewStageJobs=initialUsers.flatMap(u=>u.jobs||[]).filter(j=>["interview","final_interview"].includes(j.status)).length;
 const offers=initialUsers.flatMap(u=>u.jobs||[]).filter(j=>j.status==="offer").length;
 const redirections=initialUsers.flatMap(u=>u.jobs||[]).filter(j=>j.status==="closed").length;
 const completedTasks=initialUsers.flatMap(u=>u.tasks||[]).filter(t=>t.completed).length; async function download(d:any){setDownloading(d.id);try{const s=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {data,error}=await s.storage.from("jgojob-documents").download(d.storage_path);if(error||!data)throw error||new Error("Could not download");const url=URL.createObjectURL(data),a=document.createElement("a");a.href=url;a.download=d.original_filename||d.display_name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e:any){alert(e?.message||"Could not download document.")}finally{setDownloading(null)}}
 return <section className="min-w-0 flex-1 bg-[#f7f8f3] p-5 lg:p-9">
  <div className="mx-auto max-w-[1500px]">
   <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#7f9975]">JGO JOB ADMIN</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#2d3c30]">JGOJob</h1><p className="mt-2 max-w-2xl text-sm text-[#708075]">See who is using JGO Job and what is happening across their job search so you can support them from JGO OS.</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search email, company or job..." className="w-full rounded-xl border border-[#d7e1d0] bg-white px-4 py-3 text-sm outline-none focus:border-[#7f9975] lg:w-80"/></div>
   <section className="mt-6 rounded-2xl border border-[#dfe6db] bg-white p-5 shadow-sm lg:p-6"><div className="flex flex-col gap-2 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#7f9975]">LAUNCH LINKS</p><h2 className="mt-1 text-xl font-bold text-[#2f4234]">Copy the right link. Post. Done.</h2><p className="mt-1 text-xs text-[#748078]">Each tracked link tells JGO Job where the signup came from so your acquisition analytics stay clean.</p></div><a href="https://jgojob.com/" target="_blank" rel="noreferrer" className="text-xs font-bold text-[#607b67] underline underline-offset-4">Open JGO Job ↗</a></div><div className="mt-5 grid gap-2">{launchLinks.map(link=><div key={link.id} className="grid gap-3 rounded-xl border border-[#e4e9e1] bg-[#fafbf8] p-4 md:grid-cols-[180px_1fr_auto] md:items-center"><div><p className="text-sm font-bold text-[#344738]">{link.channel}</p><p className="mt-1 text-[10px] leading-4 text-[#7d8980]">{link.use}</p></div><code className="min-w-0 overflow-hidden text-ellipsis whitespace-nowrap rounded-lg bg-white px-3 py-2 text-[10px] text-[#66736a]">{link.url}</code><button type="button" onClick={()=>copyLaunchLink(link.id,link.url)} className="rounded-lg border border-[#cfdcc9] bg-[#eaf2e6] px-4 py-2 text-xs font-bold text-[#496044] transition hover:bg-[#e0ecdc]">{copied===link.id?"Copied ✓":"Copy link"}</button></div>)}</div></section>
   <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Signups",initialUsers.length],["Jobs tracked",totalJobs],["Interviews",totalInterviews],["Documents",totalDocs]].map(([l,n])=><div key={String(l)} className="rounded-2xl border border-[#dfe6db] bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-[#849083]">{l}</p><p className="mt-2 text-3xl font-bold text-[#334535]">{n}</p></div>)}</div>{initialAnalytics&&<section className="mt-6 rounded-2xl border border-[#dfe6db] bg-white p-5 shadow-sm lg:p-6"><div className="flex flex-col gap-2 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#7f9975]">PRODUCT ANALYTICS</p><h2 className="mt-1 text-xl font-bold text-[#2f4234]">Are people actually using JGO Job?</h2><p className="mt-1 text-xs text-[#748078]">A simple view from signup through the actions that make the product useful.</p></div><div className="flex gap-2"><div className="rounded-xl bg-[#eef4eb] px-4 py-3"><span className="block text-[9px] font-bold uppercase text-[#81907f]">New this week</span><b className="text-xl text-[#405443]">{initialAnalytics.new_7d}</b></div><div className="rounded-xl bg-[#f7eee9] px-4 py-3"><span className="block text-[9px] font-bold uppercase text-[#95847b]">Active 7 days</span><b className="text-xl text-[#405443]">{initialAnalytics.active_7d}</b></div><div className="rounded-xl bg-[#eef2f6] px-4 py-3"><span className="block text-[9px] font-bold uppercase text-[#7d8995]">Returned</span><b className="text-xl text-[#405443]">{initialAnalytics.returned_another_day}</b></div></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{funnel.map(([label,value],i)=><div key={String(label)} className="relative rounded-xl border border-[#e4e9e1] bg-[#fafbf8] p-3"><span className="text-[9px] font-bold uppercase text-[#879188]">{i+1}. {label}</span><p className="mt-1 text-2xl font-bold text-[#334535]">{value}</p>{i>0&&<p className="mt-1 text-[9px] text-[#8a958d]">{initialAnalytics.total_signups?Math.round(Number(value)/initialAnalytics.total_signups*100):0}% of signups</p>}</div>)}</div></section>}
   {initialSubscription&&<section className="mt-6 rounded-2xl border border-[#d7e1d0] bg-white p-5 shadow-sm lg:p-6"><div className="flex flex-col gap-2 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#7f9975]">PREMIUM ANALYTICS</p><h2 className="mt-1 text-xl font-bold text-[#2f4234]">Is Premium converting and retaining?</h2><p className="mt-1 text-xs text-[#748078]">Live subscription health from JGO Job billing events. History builds automatically from launch forward.</p></div><div className="rounded-xl bg-[#eef4eb] px-4 py-3"><span className="block text-[9px] font-bold uppercase text-[#81907f]">Current MRR</span><b className="text-2xl text-[#405443]">{new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(initialSubscription.mrr_cents/100)}</b></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{[["Active Premium",initialSubscription.active_premium],["Free trials",initialSubscription.total_trials],["Trial → paid",initialSubscription.trial_conversion_rate+"%"],["Cancellations",initialSubscription.cancellations],["Avg. months before cancel",initialSubscription.avg_months_before_cancel]].map(([l,n])=><div key={String(l)} className="rounded-xl border border-[#e4e9e1] bg-[#fafbf8] p-4"><p className="text-[9px] font-bold uppercase leading-4 text-[#879188]">{l}</p><p className="mt-1 text-2xl font-bold text-[#334535]">{n}</p></div>)}</div><div className="mt-4 grid gap-3 lg:grid-cols-3"><div className="rounded-xl bg-[#f4f7f1] p-4"><p className="text-[10px] font-bold uppercase text-[#879188]">Paid starts</p><b className="text-xl text-[#405443]">{initialSubscription.total_paid_starts}</b></div><div className="rounded-xl bg-[#f4f7f1] p-4"><p className="text-[10px] font-bold uppercase text-[#879188]">Converted trials</p><b className="text-xl text-[#405443]">{initialSubscription.trial_conversions}</b></div><div className="rounded-xl bg-[#f4f7f1] p-4"><p className="text-[10px] font-bold uppercase text-[#879188]">Complimentary</p><b className="text-xl text-[#405443]">{initialSubscription.complimentary}</b></div></div>{initialSubscription.monthly?.length>0&&<div className="mt-5 overflow-x-auto"><div className="min-w-[620px] overflow-hidden rounded-xl border border-[#e4e9e1]"><div className="grid grid-cols-4 bg-[#f4f7f1] px-4 py-2 text-[9px] font-bold uppercase tracking-wider text-[#829080]"><span>Month</span><span>Trials</span><span>Paid starts</span><span>Cancellations</span></div>{initialSubscription.monthly.map(m=><div key={m.month_label} className="grid grid-cols-4 border-t border-[#edf0eb] px-4 py-3 text-sm text-[#405443]"><b>{m.month_label}</b><span>{m.trials}</span><span>{m.paid}</span><span>{m.cancellations}</span></div>)}</div></div>}</section>}
   <section className="mt-6 rounded-2xl border border-[#dfe6db] bg-white p-5 shadow-sm lg:p-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#7f9975]">AT A GLANCE</p><h2 className="mt-1 text-xl font-bold text-[#2f4234]">Activation & engagement</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-[#eef4eb] p-4"><b className="text-2xl text-[#334535]">{activationPct}%</b><p className="text-xs text-[#748078]">activation rate</p></div><div className="rounded-xl bg-[#f7eee9] p-4"><b className="text-2xl text-[#334535]">{avgJobs}</b><p className="text-xs text-[#748078]">avg jobs / user</p></div><div className="rounded-xl bg-[#eef2f6] p-4"><b className="text-2xl text-[#334535]">{engagedUsers}</b><p className="text-xs text-[#748078]">engaged users</p></div><div className="rounded-xl bg-[#f3eff7] p-4"><b className="text-2xl text-[#334535]">{usersWithInterviews}</b><p className="text-xs text-[#748078]">users with interviews</p></div></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><div><p className="text-[10px] font-bold uppercase text-[#879188]">Jobs per user</p><p className="mt-2 text-sm text-[#56645b]">0 jobs: <b>{jobs0}</b> · 1 job: <b>{jobs1}</b> · 2–5: <b>{jobs2to5}</b> · 6+: <b>{jobs6plus}</b></p></div><div><p className="text-[10px] font-bold uppercase text-[#879188]">Feature adoption</p><p className="mt-2 text-sm text-[#56645b]">Tasks: <b>{Math.round(usersWithTasks/userCount*100)}%</b> · Interviews: <b>{Math.round(usersWithInterviews/userCount*100)}%</b>{initialAnalytics?<> · Find Jobs: <b>{Math.round(initialAnalytics.find_jobs_used/userCount*100)}%</b></>:null}</p></div><div><p className="text-[10px] font-bold uppercase text-[#879188]">Job-search activity</p><p className="mt-2 text-sm text-[#56645b]">Applied: <b>{appliedJobs}</b> · Interview: <b>{interviewStageJobs}</b> · Offers: <b>{offers}</b> · Redirections: <b>{redirections}</b> · Tasks done: <b>{completedTasks}</b></p></div></div></section>
   {initialDeep&&<section className="mt-6 grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-[#dfe6db] bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#7f9975]">ACTIVATION</p><p className="mt-2 text-4xl font-bold text-[#334535]">{initialDeep.activation_rate}%</p><p className="text-xs text-[#748078]">of users added at least one job</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-[#f4f7f1] p-3"><b>{initialDeep.avg_jobs_per_user}</b><br/>avg jobs/user</div><div className="rounded-xl bg-[#f4f7f1] p-3"><b>{initialDeep.users_0_jobs}</b><br/>users with 0 jobs</div></div></div><div className="rounded-2xl border border-[#dfe6db] bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#7f9975]">FEATURE ADOPTION</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs">{[["People",initialDeep.people_users],["Tasks",initialDeep.task_users],["Interviews",initialDeep.interview_users],["Outreach",initialDeep.outreach_users],["Notes",initialDeep.notes_users],["Completed tasks",initialDeep.tasks_completed]].map(([l,n])=><div key={String(l)} className="rounded-xl bg-[#fafbf8] p-3"><b className="text-lg text-[#405443]">{n}</b><br/><span className="text-[#748078]">{l}</span></div>)}</div></div><div className="rounded-2xl border border-[#dfe6db] bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#7f9975]">OUTCOMES</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs">{[["Jobs",initialDeep.total_jobs],["Applied",initialDeep.applied_jobs],["Interview stage",initialDeep.interview_jobs],["Offers",initialDeep.offer_jobs],["Redirections",initialDeep.closed_jobs],["Returned 2+ days",initialDeep.retained_2plus_days]].map(([l,n])=><div key={String(l)} className="rounded-xl bg-[#fafbf8] p-3"><b className="text-lg text-[#405443]">{n}</b><br/><span className="text-[#748078]">{l}</span></div>)}</div></div></section>}
   {initialAttribution.length>0&&<section className="mt-6 rounded-2xl border border-[#dfe6db] bg-white p-5 shadow-sm lg:p-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#7f9975]">ACQUISITION</p><h2 className="mt-1 text-xl font-bold text-[#2f4234]">Where users are coming from</h2><p className="mt-1 text-xs text-[#748078]">Signup attribution captured when someone first reaches JGO Job.</p><div className="mt-5 overflow-hidden rounded-xl border border-[#e4e9e1]"><div className="grid grid-cols-[1fr_1fr_auto_auto_auto] gap-3 bg-[#f4f7f1] px-4 py-2 text-[9px] font-bold uppercase tracking-wider text-[#829080]"><span>Source</span><span>Campaign</span><span>Signups</span><span>Activated</span><span>Returned</span></div>{initialSourceQuality.map((row,i)=><div key={row.source+"-"+row.campaign+"-"+i} className="grid grid-cols-[1fr_1fr_auto_auto_auto] gap-3 border-t border-[#edf0eb] px-4 py-3 text-sm"><b className="text-[#344738]">{row.source}</b><span className="text-[#6f7b73]">{row.campaign}</span><b className="text-right text-[#405443]">{row.signups}</b><span className="text-right text-[#405443]">{row.activated} ({row.activation_rate}%)</span><span className="text-right text-[#405443]">{row.retained}</span></div>)}</div></section>}
   <div className="mt-6 space-y-3">{users.map(u=>{const isOpen=open===u.user_id;return <article key={u.user_id} className="overflow-hidden rounded-2xl border border-[#dfe6db] bg-white shadow-sm">
    <button onClick={()=>setOpen(isOpen?null:u.user_id)} className="grid w-full gap-3 p-5 text-left hover:bg-[#fafbf8] md:grid-cols-[1.5fr_.65fr_.65fr_.65fr_.8fr_auto] md:items-center">
     <div><p className="font-bold text-[#2f4234]">{u.email}</p><p className="mt-1 text-[11px] text-[#879188]">Joined {fmt(u.signup_at)}</p></div><div><span className="text-[9px] font-bold uppercase text-[#929c94]">Jobs</span><p className="font-bold text-[#405443]">{u.jobs?.length||0}</p></div><div><span className="text-[9px] font-bold uppercase text-[#929c94]">Interviews</span><p className="font-bold text-[#405443]">{u.interviews?.length||0}</p></div><div><span className="text-[9px] font-bold uppercase text-[#929c94]">Docs</span><p className="font-bold text-[#405443]">{u.documents?.length||0}</p></div><div><span className="text-[9px] font-bold uppercase text-[#929c94]">Last login</span><p className="text-xs font-semibold text-[#59675e]">{fmt(u.last_sign_in_at)}</p></div><span className="text-xl text-[#718176]">{isOpen?"−":"+"}</span>
    </button>
    {isOpen&&<div className="border-t border-[#e7ece5] bg-[#fbfcf9] p-5">
     <div className="grid gap-5 xl:grid-cols-2">
      <div><h2 className="text-sm font-bold text-[#344738]">Jobs</h2><div className="mt-3 space-y-2">{u.jobs?.length?u.jobs.map(j=><div key={j.id} className="rounded-xl border border-[#e1e7df] bg-white p-4"><div className="flex justify-between gap-3"><div><p className="font-bold text-[#334535]">{j.company}</p><p className="text-sm text-[#66736a]">{j.title}</p></div><span className="h-fit rounded-full bg-[#e8efe5] px-3 py-1 text-[10px] font-bold text-[#52684b]">{String(j.status||"saved").replaceAll("_"," ")}</span></div>{j.location&&<p className="mt-2 text-xs text-[#89928b]">{j.location}</p>}{j.next_action&&<p className="mt-2 text-xs"><b>Next:</b> {j.next_action} {j.next_action_date?"· "+j.next_action_date:""}</p>}</div>):<p className="text-xs text-[#8a958d]">No jobs added yet.</p>}</div></div>
      <div><h2 className="text-sm font-bold text-[#344738]">Documents</h2><div className="mt-3 space-y-2">{u.documents?.length?u.documents.map(d=><div key={d.id} className="flex items-center gap-3 rounded-xl border border-[#e1e7df] bg-white p-4"><div className="min-w-0 flex-1"><p className="truncate font-bold text-[#334535]">{d.display_name}</p><p className="truncate text-[11px] text-[#879188]">{d.document_type} · {d.original_filename}</p></div><button onClick={()=>download(d)} disabled={downloading===d.id} className="rounded-lg bg-[#647d5b] px-3 py-2 text-xs font-bold text-white">{downloading===d.id?"Opening...":"Download"}</button></div>):<p className="text-xs text-[#8a958d]">No documents uploaded yet.</p>}</div></div>
      <div><h2 className="text-sm font-bold text-[#344738]">Interviews</h2><div className="mt-3 space-y-2">{u.interviews?.length?u.interviews.map(i=><div key={i.id} className="rounded-xl border border-[#e1e7df] bg-white p-4"><p className="font-bold text-[#334535]">{i.round_label||i.interview_type||"Interview"}</p><p className="mt-1 text-xs text-[#6f7b73]">{fmt(i.interview_at)}{i.interviewer?" · "+i.interviewer:""}</p>{i.status&&<p className="mt-1 text-[11px] font-semibold text-[#708075]">{i.status}</p>}</div>):<p className="text-xs text-[#8a958d]">No interviews yet.</p>}</div></div>
      <div><h2 className="text-sm font-bold text-[#344738]">Tasks & follow-ups</h2><div className="mt-3 space-y-2">{u.tasks?.length?u.tasks.map(t=><div key={t.id} className="flex gap-3 rounded-xl border border-[#e1e7df] bg-white p-4"><span className="font-bold text-[#647d5b]">{t.completed?"✓":"○"}</span><div><p className={"text-sm font-semibold "+(t.completed?"text-[#8d978f] line-through":"text-[#334535]")}>{t.title}</p>{t.due_date&&<p className="mt-1 text-[11px] text-[#879188]">Due {t.due_date}</p>}</div></div>):<p className="text-xs text-[#8a958d]">No tasks yet.</p>}</div></div>
     </div>
    </div>}
   </article>})}{users.length===0&&<div className="rounded-2xl border border-dashed border-[#d5ded2] bg-white p-10 text-center text-sm text-[#7b887d]">No JGO Job users match this search.</div>}</div>
  </div>
 </section>
}
