"use client";
import {useMemo,useState} from "react";
import {createBrowserClient} from "@supabase/ssr";

type Row={user_id:string;email:string;signup_at:string;last_sign_in_at:string|null;jobs:any[];interviews:any[];tasks:any[];documents:any[]};
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}):"Never";
type Analytics={total_signups:number;tour_completed:number;first_job_added:number;person_added:number;task_added:number;interview_added:number;find_jobs_used:number;returned_another_day:number;active_7d:number;new_7d:number};\nexport default function JgoJobAdmin({initialUsers,initialAnalytics}:{initialUsers:Row[];initialAnalytics:Analytics|null}){
 const [q,setQ]=useState(""),[open,setOpen]=useState<string|null>(null),[downloading,setDownloading]=useState<string|null>(null);
 const users=useMemo(()=>initialUsers.filter(u=>u.email?.toLowerCase().includes(q.toLowerCase())||u.jobs?.some(j=>(j.company+" "+j.title).toLowerCase().includes(q.toLowerCase()))),[q,initialUsers]);
 const totalJobs=initialUsers.reduce((n,u)=>n+(u.jobs?.length||0),0), totalDocs=initialUsers.reduce((n,u)=>n+(u.documents?.length||0),0), totalInterviews=initialUsers.reduce((n,u)=>n+(u.interviews?.length||0),0);\n const funnel: Array<[string,number]> = initialAnalytics ? [["Signed up",initialAnalytics.total_signups],["Tour done",initialAnalytics.tour_completed],["First job",initialAnalytics.first_job_added],["Person",initialAnalytics.person_added],["Task",initialAnalytics.task_added],["Interview",initialAnalytics.interview_added],["Find Jobs",initialAnalytics.find_jobs_used],["Returned",initialAnalytics.returned_another_day]] : [];
 async function download(d:any){setDownloading(d.id);try{const s=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {data,error}=await s.storage.from("jgojob-documents").download(d.storage_path);if(error||!data)throw error||new Error("Could not download");const url=URL.createObjectURL(data),a=document.createElement("a");a.href=url;a.download=d.original_filename||d.display_name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e:any){alert(e?.message||"Could not download document.")}finally{setDownloading(null)}}
 return <section className="min-w-0 flex-1 bg-[#f7f8f3] p-5 lg:p-9">
  <div className="mx-auto max-w-[1500px]">
   <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#7f9975]">JGO JOB ADMIN</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#2d3c30]">JGOJob</h1><p className="mt-2 max-w-2xl text-sm text-[#708075]">See who is using JGO Job and what is happening across their job search so you can support them from JGO OS.</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search email, company or job..." className="w-full rounded-xl border border-[#d7e1d0] bg-white px-4 py-3 text-sm outline-none focus:border-[#7f9975] lg:w-80"/></div>
   <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Signups",initialUsers.length],["Jobs tracked",totalJobs],["Interviews",totalInterviews],["Documents",totalDocs]].map(([l,n])=><div key={String(l)} className="rounded-2xl border border-[#dfe6db] bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-[#849083]">{l}</p><p className="mt-2 text-3xl font-bold text-[#334535]">{n}</p></div>)}</div>{initialAnalytics&&<section className="mt-6 rounded-2xl border border-[#dfe6db] bg-white p-5 shadow-sm lg:p-6"><div className="flex flex-col gap-2 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#7f9975]">PRODUCT ANALYTICS</p><h2 className="mt-1 text-xl font-bold text-[#2f4234]">Are people actually using JGO Job?</h2><p className="mt-1 text-xs text-[#748078]">A simple view from signup through the actions that make the product useful.</p></div><div className="flex gap-2"><div className="rounded-xl bg-[#eef4eb] px-4 py-3"><span className="block text-[9px] font-bold uppercase text-[#81907f]">New this week</span><b className="text-xl text-[#405443]">{initialAnalytics.new_7d}</b></div><div className="rounded-xl bg-[#f7eee9] px-4 py-3"><span className="block text-[9px] font-bold uppercase text-[#95847b]">Active 7 days</span><b className="text-xl text-[#405443]">{initialAnalytics.active_7d}</b></div><div className="rounded-xl bg-[#eef2f6] px-4 py-3"><span className="block text-[9px] font-bold uppercase text-[#7d8995]">Returned</span><b className="text-xl text-[#405443]">{initialAnalytics.returned_another_day}</b></div></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{funnel.map(([label,value],i)=><div key={String(label)} className="relative rounded-xl border border-[#e4e9e1] bg-[#fafbf8] p-3"><span className="text-[9px] font-bold uppercase text-[#879188]">{i+1}. {label}</span><p className="mt-1 text-2xl font-bold text-[#334535]">{value}</p>{i>0&&<p className="mt-1 text-[9px] text-[#8a958d]">{initialAnalytics.total_signups?Math.round(Number(value)/initialAnalytics.total_signups*100):0}% of signups</p>}</div>)}</div></section>}
   <div className="mt-6 space-y-3">{users.map(u=>{const isOpen=open===u.user_id;return <article key={u.user_id} className="overflow-hidden rounded-2xl border border-[#dfe6db] bg-white shadow-sm">
    <button onClick={()=>setOpen(isOpen?null:u.user_id)} className="grid w-full gap-3 p-5 text-left hover:bg-[#fafbf8] md:grid-cols-[1.5fr_.65fr_.65fr_.65fr_.8fr_auto] md:items-center">
     <div><p className="font-bold text-[#2f4234]">{u.email}</p><p className="mt-1 text-[11px] text-[#879188]">Joined {fmt(u.signup_at)}</p></div><div><span className="text-[9px] font-bold uppercase text-[#929c94]">Jobs</span><p className="font-bold text-[#405443]">{u.jobs?.length||0}</p></div><div><span className="text-[9px] font-bold uppercase text-[#929c94]">Interviews</span><p className="font-bold text-[#405443]">{u.interviews?.length||0}</p></div><div><span className="text-[9px] font-bold uppercase text-[#929c94]">Docs</span><p className="font-bold text-[#405443]">{u.documents?.length||0}</p></div><div><span className="text-[9px] font-bold uppercase text-[#929c94]">Last login</span><p className="text-xs font-semibold text-[#59675e]">{fmt(u.last_sign_in_at)}</p></div><span className="text-xl text-[#718176]">{isOpen?"−":"+"}</span>
    </button>
    {isOpen&&<div className="border-t border-[#e7ece5] bg-[#fbfcf9] p-5">
     <div className="grid gap-5 xl:grid-cols-2">
      <div><h2 className="text-sm font-bold text-[#344738]">Jobs</h2><div className="mt-3 space-y-2">{u.jobs?.length?u.jobs.map(j=><div key={j.id} className="rounded-xl border border-[#e1e7df] bg-white p-4"><div className="flex justify-between gap-3"><div><p className="font-bold text-[#334535]">{j.company}</p><p className="text-sm text-[#66736a]">{j.title}</p></div><span className="h-fit rounded-full bg-[#e8efe5] px-3 py-1 text-[10px] font-bold text-[#52684b]">{String(j.status||"saved").replaceAll("_"," ")}</span></div>{j.location&&<p className="mt-2 text-xs text-[#89928b]">{j.location}</p>}{j.next_action&&<p className="mt-2 text-xs"><b>Next:</b> {j.next_action} {j.next_action_date?"· "+j.next_action_date:""}</p>}</div>):<p className="text-xs text-[#8a958d]">No jobs added yet.</p>}</div></div>
      <div><h2 className="text-sm font-bold text-[#344738]">Documents</h2><div className="mt-3 space-y-2">{u.documents?.length?u.documents.map(d=><div key={d.id} className="flex items-center gap-3 rounded-xl border border-[#e1e7df] bg-white p-4"><div className="min-w-0 flex-1"><p className="truncate font-bold text-[#334535]">{d.display_name}</p><p className="truncate text-[11px] text-[#879188]">{d.document_type} · {d.original_filename}</p></div><button onClick={()=>download(d)} disabled={downloading===d.id} className="rounded-lg bg-[#647d5b] px-3 py-2 text-xs font-bold text-white">{downloading===d.id?"Opening...":"Download"}</button></div>):<p className="text-xs text-[#8a958d]">No documents uploaded yet.</p>}</div></div>
      <div><h2 className="text-sm font-bold text-[#344738]">Interviews</h2><div className="mt-3 space-y-2">{u.interviews?.length?u.interviews.map(i=><div key={i.id} className="rounded-xl border border-[#e1e7df] bg-white p-4"><p className="font-bold text-[#334535]">{i.round_label||i.interview_type||"Interview"}</p><p className="mt-1 text-xs text-[#6f7b73]">{fmt(i.interview_at)}{i.interviewer?" · "+i.interviewer:""}</p>{i.status&&<p className="mt-1 text-[11px] font-semibold text-[#708075]">{i.status}</p>}</div>):<p className="text-xs text-[#8a958d]">No interviews yet.</p>}</div></div>
      <div><h2 className="text-sm font-bold text-[#344738]">Tasks & follow-ups</h2><div className="mt-3 space-y-2">{u.tasks?.length?u.tasks.map(t=><div key={t.id} className="flex gap-3 rounded-xl border border-[#e1e7df] bg-white p-4"><span className="font-bold text-[#647d5b]">{t.completed?"✓":"○"}</span><div><p className={"text-sm font-semibold "+(t.completed?"text-[#8d978f] line-through":"text-[#334535]")}>{t.title}</p>{t.due_date&&<p className="mt-1 text-[11px] text-[#879188]">Due {t.due_date}</p>}</div></div>):<p className="text-xs text-[#8a958d]">No tasks yet.</p>}</div></div>
     </div>
    </div>}
   </article>})}{users.length===0&&<div className="rounded-2xl border border-dashed border-[#d5ded2] bg-white p-10 text-center text-sm text-[#7b887d]">No JGO Job users match this search.</div>}</div>
  </div>
 </section>
}
