create table if not exists email_contacts (
  id bigint generated by default as identity primary key,
  name text,
  email text not null unique,
  company text,
  source text not null default 'email',
  client_id bigint references clients(id) on delete set null,
  first_contacted_at timestamptz,
  last_contacted_at timestamptz,
  email_count integer not null default 0,
  marketing_opt_in boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists email_contacts_last_contacted_idx
on email_contacts(last_contacted_at desc);

create index if not exists email_contacts_client_id_idx
on email_contacts(client_id);

alter table email_contacts enable row level security;

create policy "Authenticated users can manage email contacts"
on email_contacts
for all
to authenticated
using (true)
with check (true);
