import { NextResponse } from "next/server";
import Stripe from "stripe";
import { Resend } from "resend";
import { createClient } from "@/lib/supabase-server";
export const runtime="nodejs";export const dynamic="force-dynamic";
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const resend=process.env.RESEND_API_KEY?new Resend(process.env.RESEND_API_KEY):null;
const VENMO_URL="https://venmo.com/u/jengordon",VENMO_HANDLE="@jengordon",ZELLE_NUMBER="908-477-5032",CARD_FEE_RATE=.03;
type InvoiceRequest={clientId?:number;clientName?:string;clientEmail?:string;service?:string;price?:number;message?:string};
const esc=(v:string)=>v.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const currency=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
export async function POST(request:Request){if(!stripe)return NextResponse.json({error:"Stripe is not configured.",detail:"Missing STRIPE_SECRET_KEY."},{status:500});if(!resend)return NextResponse.json({error:"Email is not configured.",detail:"Missing RESEND_API_KEY."},{status:500});let body:InvoiceRequest;try{body=await request.json()}catch{return NextResponse.json({error:"Invalid request body."},{status:400})}
const clientId=Number(body.clientId),clientName=String(body.clientName||"").trim(),clientEmail=String(body.clientEmail||"").trim().toLowerCase(),service=String(body.service||"").trim(),price=Number(body.price),message=String(body.message||"").trim();if(!Number.isInteger(clientId)||clientId<=0)return NextResponse.json({error:"Invalid client ID."},{status:400});if(!clientName||!clientEmail||!service)return NextResponse.json({error:"Client name, client email, and service are required."},{status:400});if(!Number.isFinite(price)||price<=0||price>100000)return NextResponse.json({error:"Enter a valid invoice price."},{status:400});
const supabase=await createClient();const{data:client,error:clientError}=await supabase.from("clients").select("id,name,email,status").eq("id",clientId).maybeSingle();if(clientError||!client)return NextResponse.json({error:"Client could not be found.",detail:clientError?.message},{status:404});
const base=Math.round(price*100),cardCents=Math.round(base*(1+CARD_FEE_RATE)),fee=(cardCents-base)/100,cardTotal=cardCents/100;
try{const checkout=await stripe.checkout.sessions.create({mode:"payment",customer_email:clientEmail,client_reference_id:String(clientId),success_url:"https://www.jgohire.com/?payment=success",cancel_url:"https://www.jgohire.com/?payment=cancelled",line_items:[{quantity:1,price_data:{currency:"usd",unit_amount:cardCents,product_data:{name:`JGO Hire: ${service}`,description:`${currency(price)} service + ${currency(fee)} card processing fee`}}}],metadata:{source:"jgo_os_invoice",client_id:String(clientId),client_name:clientName,client_email:clientEmail,service,base_price:price.toFixed(2),card_fee:fee.toFixed(2)}});if(!checkout.url)throw new Error("Stripe did not return a checkout URL.");
const{data:existing,error:lookupError}=await supabase.from("client_services").select("id,payment_status").eq("client_id",clientId).eq("service",service).order("date_added",{ascending:false}).limit(10);if(lookupError)throw new Error(lookupError.message);const reusable=(existing??[]).find(i=>String(i.payment_status||"").trim().toLowerCase()!=="paid");let serviceId:number;if(reusable){const{error}=await supabase.from("client_services").update({price,payment_status:"Invoice Sent",status:"Selected",date_added:new Date().toISOString().slice(0,10),notes:message||null}).eq("id",reusable.id).eq("client_id",clientId);if(error)throw new Error(error.message);serviceId=reusable.id}else{const{data,error}=await supabase.from("client_services").insert({client_id:clientId,service,price,status:"Selected",payment_status:"Invoice Sent",date_added:new Date().toISOString().slice(0,10),scheduled_date:null,notes:message||null}).select("id").single();if(error||!data)throw new Error(error?.message||"Unable to save invoice service.");serviceId=data.id}
if(["lead","free 15 scheduled","free 15 completed"].includes(String(client.status||"lead").trim().toLowerCase()))await supabase.from("clients").update({status:"Active"}).eq("id",clientId);
const first=clientName.split(/\s+/)[0]||clientName;const paymentText=`Venmo (no fee): ${VENMO_HANDLE}\n${VENMO_URL}\n\nZelle (preferred, no fee): ${ZELLE_NUMBER}\n\nCard: ${currency(cardTotal)} including ${currency(fee)} processing fee\n${checkout.url}`;
const email=await resend.emails.send({from:"JGO Hire <jen@jgohire.com>",to:[clientEmail],replyTo:"jen@jgohire.com",subject:`Invoice from JGO Hire: ${service}`,text:`Hi ${first},\n\n${message||"Thank you for choosing JGO Hire. Your invoice and payment options are below."}\n\nService: ${service}\nAmount due: ${currency(price)}\n\n${paymentText}\n\nBest,\nJen\nJGO Hire`,html:`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;color:#243128"><div style="background:#e6eee1;padding:28px;border-radius:20px"><p style="margin:0;color:#53684c;font-weight:700">JGO HIRE</p><h1 style="margin:8px 0">Invoice</h1><p>Hi ${esc(first)},</p><p>${esc(message||"Thank you for choosing JGO Hire. Your invoice and payment options are below.")}</p></div><div style="padding:24px"><p><strong>Service:</strong> ${esc(service)}</p><p><strong>Amount due:</strong> ${esc(currency(price))}</p><hr/><h2>Payment options</h2><p><strong>Venmo, no fee:</strong> ${esc(VENMO_HANDLE)}<br/><a href="${esc(VENMO_URL)}">Pay with Venmo</a></p><p><strong>Zelle, preferred and no fee:</strong> ${esc(ZELLE_NUMBER)}</p><p><strong>Card:</strong> ${esc(currency(cardTotal))} including ${esc(currency(fee))} processing fee<br/><a href="${esc(checkout.url)}">Pay securely by card</a></p><p>Best,<br/>Jen<br/>JGO Hire</p></div></div>`});
if(email.error){await supabase.from("client_services").update({payment_status:"Open"}).eq("id",serviceId).eq("client_id",clientId);throw new Error(`Resend error: ${JSON.stringify(email.error)}`)}
console.info("JGO invoice accepted by Resend",{emailId:email.data?.id,recipient:clientEmail,serviceId});return NextResponse.json({sent:true,accepted:true,serviceId,checkoutUrl:checkout.url,emailId:email.data?.id??null,recipient:clientEmail,message:"Invoice accepted by email provider."});
}catch(error){const detail=error instanceof Error?error.message:"Unknown error";console.error("Unable to send JGO Hire invoice:",error);return NextResponse.json({error:"Unable to send the invoice.",detail},{status:500})}}
