"use client";

import { useMemo, useState } from "react";

declare global { interface Window { jspdf?: any } }

type Change = { title: string; body: string };
type TargetRole = { company: string; role: string; alignment: string };
type ReportData = {
  client: string; transformationBefore: string; transformationAfter: string; changes: Change[]; targetRoles: TargetRole[];
  sellingPoints: string[]; biggestDifferenceBefore: string; biggestDifferenceNow: string; positioning: string; targetLevel: string;
  primaryAlignment: string; industries: string; differentiators: string; status: string;
};

const emptyReport: ReportData = { client:"", transformationBefore:"", transformationAfter:"", changes:[], targetRoles:[], sellingPoints:[], biggestDifferenceBefore:"", biggestDifferenceNow:"", positioning:"", targetLevel:"", primaryAlignment:"", industries:"", differentiators:"", status:"READY" };

function clean(v:string){return v.replace(/^#{1,6}\s*/,"").replace(/^\*\*(.*?)\*\*$/,"$1").replace(/\*\*/g,"").trim();}
function cleanBullet(v:string){return clean(v).replace(/^[•●▪◦\-*]\s*/,"").trim();}
function splitLines(v:string){return v.split(/\n+/).map(cleanBullet).filter(Boolean);}
function sentenceBullets(v:string){return v.replace(/\s+/g," ").trim().split(/(?<=[.!?])\s+(?=[A-Z0-9])/).map(cleanBullet).filter(Boolean);}
function fileBaseName(name:string){const n=name.replace(/[^a-zA-Z0-9 .'-]/g,"").replace(/\s+/g," ").trim();return `${n||"JGO Hire"} Resume Ready Report`;}
function normalizeTag(line:string){const m=line.trim().match(/^\[\/?([A-Z0-9_ &-]+)\]$/i);return m?m[1].toUpperCase().replace(/[ &-]+/g,"_"):null;}
function getTaggedBlocks(raw:string){const lines=raw.replace(/\r/g,"").split("\n");const blocks:{tag:string;value:string}[]=[];let tag="";let buf:string[]=[];const flush=()=>{if(tag)blocks.push({tag,value:buf.join("\n").trim()});buf=[];};for(const line of lines){const t=normalizeTag(line);if(t){if(t==="JGO_REPORT")continue;flush();tag=t;}else if(tag)buf.push(line);}flush();return blocks;}
function parseStructured(raw:string):ReportData|null{
  if(!/\[JGO_REPORT\]/i.test(raw)&&!/\[TRANSFORMATION_BEFORE\]/i.test(raw))return null;
  const out:ReportData={...emptyReport,changes:[],targetRoles:[],sellingPoints:[]};let currentChange:Partial<Change>|null=null;let currentRole:Partial<TargetRole>|null=null;
  const pushChange=()=>{if(currentChange&&(currentChange.title||currentChange.body))out.changes.push({title:currentChange.title||"Resume Improvement",body:currentChange.body||""});currentChange=null;};
  const pushRole=()=>{if(currentRole&&(currentRole.company||currentRole.role||currentRole.alignment))out.targetRoles.push({company:currentRole.company||"",role:currentRole.role||"",alignment:currentRole.alignment||""});currentRole=null;};
  for(const b of getTaggedBlocks(raw)){const v=b.value.trim();switch(b.tag){case"CLIENT":out.client=v;break;case"TRANSFORMATION_BEFORE":out.transformationBefore=v;break;case"TRANSFORMATION_AFTER":out.transformationAfter=v;break;case"CHANGE":pushChange();currentChange={};break;case"TITLE":if(currentChange)currentChange.title=v;break;case"BODY":if(currentChange)currentChange.body=v;break;case"TARGET_ROLE":pushRole();currentRole={};break;case"COMPANY":if(currentRole)currentRole.company=v;break;case"ROLE":if(currentRole)currentRole.role=v;break;case"ALIGNMENT":if(currentRole)currentRole.alignment=v;break;case"SELLING_POINTS":out.sellingPoints=splitLines(v);break;case"BIGGEST_DIFFERENCE_BEFORE":out.biggestDifferenceBefore=v;break;case"BIGGEST_DIFFERENCE_NOW":out.biggestDifferenceNow=v;break;case"POSITIONING":out.positioning=v;break;case"TARGET_LEVEL":out.targetLevel=v;break;case"PRIMARY_ALIGNMENT":out.primaryAlignment=v;break;case"INDUSTRIES":out.industries=v;break;case"DIFFERENTIATORS":out.differentiators=v;break;case"STATUS":out.status=v||"READY";break;}}
  pushChange();pushRole();return out;
}
function parseLegacy(raw:string):ReportData{
  const out:ReportData={...emptyReport,changes:[],targetRoles:[],sellingPoints:[]};const lines=raw.replace(/\r/g,"").split("\n");let section="",sub="";let buf:string[]=[];
  const flush=()=>{const text=buf.map(clean).filter(Boolean).join("\n").trim();if(!text){buf=[];return;}if(section==="BEFORE")out.transformationBefore=text;else if(section==="AFTER")out.transformationAfter=text;else if(section==="SELLING")out.sellingPoints=splitLines(text);else if(section==="CHANGE"&&sub)out.changes.push({title:sub,body:text});else if(section==="TARGET"&&sub){const [company,...r]=sub.split("|").map(x=>x.trim());out.targetRoles.push({company,role:r.join(" | "),alignment:text});}buf=[];};
  for(const rawLine of lines){const line=clean(rawLine);if(!line)continue;const up=line.toUpperCase().replace(/:$/,"");if(/^PREPARED FOR\s+/i.test(line)){out.client=line.replace(/^PREPARED FOR\s+/i,"").trim();continue;}if(/^CLIENT\s*:/i.test(line)){out.client=line.replace(/^CLIENT\s*:/i,"").trim();continue;}if(up==="BEFORE"){flush();section="BEFORE";sub="";continue;}if(up==="AFTER"){flush();section="AFTER";sub="";continue;}if(up==="TARGET ROLE ALIGNMENT"){flush();section="TARGET";sub="";continue;}if(up==="YOUR STRONGEST SELLING POINTS"){flush();section="SELLING";sub="";continue;}if(up==="THE BIGGEST DIFFERENCE"){flush();section="DIFFERENCE";sub="";continue;}if(up==="JGO HIRE FINAL ASSESSMENT"){flush();section="FINAL";sub="";continue;}if(/^\d+\.\s+/.test(line)){flush();section="CHANGE";sub=line.replace(/^\d+\.\s+/,"").trim();continue;}if(section==="TARGET"&&/\|/.test(line)&&!line.endsWith(".")){flush();sub=line;continue;}if(section==="DIFFERENCE"){if(/^BEFORE\s*:/i.test(line))out.biggestDifferenceBefore=line.replace(/^BEFORE\s*:/i,"").trim();else if(/^(NOW|AFTER)\s*:/i.test(line))out.biggestDifferenceNow=line.replace(/^(NOW|AFTER)\s*:/i,"").trim();continue;}if(section==="FINAL"){if(/^RESUME POSITIONING\s*:/i.test(line))out.positioning=line.replace(/^RESUME POSITIONING\s*:/i,"").trim();else if(/^TARGET LEVEL\s*:/i.test(line))out.targetLevel=line.replace(/^TARGET LEVEL\s*:/i,"").trim();else if(/^PRIMARY AREAS OF ALIGNMENT\s*:/i.test(line))out.primaryAlignment=line.replace(/^PRIMARY AREAS OF ALIGNMENT\s*:/i,"").trim();else if(/^INDUSTRY STRENGTHS\s*:/i.test(line))out.industries=line.replace(/^INDUSTRY STRENGTHS\s*:/i,"").trim();else if(/^KEY DIFFERENTIATORS\s*:/i.test(line))out.differentiators=line.replace(/^KEY DIFFERENTIATORS\s*:/i,"").trim();else if(/^RESUME STATUS\s*:/i.test(line))out.status=line.replace(/^RESUME STATUS\s*:/i,"").trim();continue;}if(!["YOUR RESUME TRANSFORMATION","WHAT CHANGED"].includes(up))buf.push(line);}flush();return out;
}
function parseImport(raw:string){return parseStructured(raw)||parseLegacy(raw);}

function Field({label,value,onChange,rows=4}:{label:string;value:string;onChange:(v:string)=>void;rows?:number}){return <label className="block"><span className="mb-2 block text-[11px] font-bold uppercase tracking-[0.14em] text-[#71806f]">{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} rows={rows} className="w-full resize-y rounded-2xl border border-[#dce4d8] bg-white px-4 py-3 text-sm leading-6 text-[#364234] outline-none focus:border-[#aebda8] focus:ring-4 focus:ring-[#dfe8da]/60"/></label>}
function Input({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-[11px] font-bold uppercase tracking-[0.14em] text-[#71806f]">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-[#dce4d8] bg-white px-4 py-3 text-sm text-[#364234] outline-none focus:border-[#aebda8] focus:ring-4 focus:ring-[#dfe8da]/60"/></label>}
function loadScript(src:string,id:string){return new Promise<void>((resolve,reject)=>{const ex=document.getElementById(id) as HTMLScriptElement|null;if(ex){if(ex.dataset.loaded==="true")return resolve();ex.addEventListener("load",()=>resolve(),{once:true});ex.addEventListener("error",()=>reject(new Error("Could not load PDF tools.")),{once:true});return;}const s=document.createElement("script");s.id=id;s.src=src;s.async=true;s.onload=()=>{s.dataset.loaded="true";resolve();};s.onerror=()=>reject(new Error("Could not load PDF tools."));document.head.appendChild(s);});}
async function imageData(url:string){const blob=await fetch(url).then(r=>{if(!r.ok)throw new Error("Logo not found");return r.blob();});return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob);});}

async function makePdf(data:ReportData){
  await loadScript("https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js","jgo-report-jspdf");const jsPDF=window.jspdf?.jsPDF;if(!jsPDF)throw new Error("PDF generator did not load.");
  const d=new jsPDF({unit:"pt",format:"letter",orientation:"portrait"});const W=612,H=792,M=34,CW=W-M*2,G=18,COL=(CW-G)/2,BOTTOM=748;
  const sage:[number,number,number]=[77,98,72],charcoal:[number,number,number]=[45,52,44],muted:[number,number,number]=[108,118,106],light:[number,number,number]=[240,244,237],pale:[number,number,number]=[248,250,246],rule:[number,number,number]=[218,224,214];
  const txt=(size:number,bold=false,color=charcoal)=>{d.setFont("helvetica",bold?"bold":"normal");d.setFontSize(size);d.setTextColor(...color);};
  const footer=(p:number)=>{d.setDrawColor(...rule);d.line(M,764,W-M,764);txt(6.5,true,muted);d.text("JGO HIRE  |  RESUME READY REPORT",M,779);d.text(`${p} / 2`,W-M,779,{align:"right"});};
  const section=(name:string,x:number,y:number,w:number)=>{txt(8.2,true,sage);d.text(name,x,y);d.setDrawColor(...rule);d.line(x,y+5,x+w,y+5);return y+18;};
  const measureLines=(text:string,w:number,size:number,bold=false)=>{txt(size,bold);return d.splitTextToSize(text,w) as string[];};
  const drawParagraph=(text:string,x:number,y:number,w:number,size=7.3,bold=false,leading=1.28)=>{if(!text)return y;const lines=measureLines(text,w,size,bold);txt(size,bold);d.text(lines,x,y);return y+lines.length*size*leading;};
  const drawBullet=(text:string,x:number,y:number,w:number,size=7.15)=>{const lines=measureLines(text,w-13,size,false);const lh=size*1.28;txt(size,false);d.setFillColor(...sage);d.circle(x+2,y-2,1.25,"F");d.text(lines,x+11,y);return y+lines.length*lh+4;};
  const drawBullets=(items:string[],x:number,y:number,w:number,maxY:number,size=7.15)=>{for(const item of items.filter(Boolean)){const lines=measureLines(item,w-13,size,false);const needed=lines.length*size*1.28+4;if(y+needed>maxY)break;y=drawBullet(item,x,y,w,size);}return y;};
  const pill=(label:string,x:number,y:number)=>{txt(6.4,true,sage);const w=Math.max(42,d.getTextWidth(label)+16);d.setFillColor(...light);d.roundedRect(x,y-9,w,15,7,7,"F");d.text(label,x+8,y+1);};
  const header=async(p:number)=>{if(p===1){try{const logo=await imageData("/jgo-hire-logo.png");d.addImage(logo,"PNG",M,28,72,28,undefined,"FAST");}catch{txt(17,true);d.text("JGO Hire",M,49);}txt(7,true,sage);d.text("RESUME READY REPORT",W-M,36,{align:"right"});txt(19,true,[30,34,29]);d.text(data.client||"Client",W-M,56,{align:"right"});d.setFillColor(...sage);d.rect(M,70,CW,3,"F");}else{txt(8,true,sage);d.text("JGO HIRE",M,36);txt(14,true,[30,34,29]);d.text("Resume Ready Report",M,54);txt(8,true,muted);d.text(data.client||"Client",W-M,52,{align:"right"});d.setDrawColor(...rule);d.line(M,67,W-M,67);}};

  await header(1);let y=94;
  y=section("YOUR RESUME TRANSFORMATION",M,y,CW);const boxY=y,boxH=134;
  d.setFillColor(...pale);d.roundedRect(M,boxY,COL,boxH,9,9,"F");d.setFillColor(...light);d.roundedRect(M+COL+G,boxY,COL,boxH,9,9,"F");pill("BEFORE",M+12,boxY+20);pill("AFTER",M+COL+G+12,boxY+20);
  drawBullets(sentenceBullets(data.transformationBefore),M+12,boxY+45,COL-24,boxY+boxH-12,7.0);drawBullets(sentenceBullets(data.transformationAfter),M+COL+G+12,boxY+45,COL-24,boxY+boxH-12,7.0);
  y=boxY+boxH+23;y=section("WHAT CHANGED",M,y,CW);
  let col=0,cy=[y,y];const xs=[M,M+COL+G];const maxY=BOTTOM;
  for(let i=0;i<data.changes.length;i++){
    const c=data.changes[i];const bullets=sentenceBullets(c.body);const titleLines=measureLines(`${i+1}. ${c.title.toUpperCase()}`,COL-8,7.2,true);const bulletHeights=bullets.map(b=>measureLines(b,COL-21,6.8).length*6.8*1.28+4);const estimated=titleLines.length*9.2+8+bulletHeights.reduce((a,b)=>a+b,0)+10;
    if(cy[col]+estimated>maxY&&col===0){col=1;}if(cy[col]+estimated>maxY)break;
    const x=xs[col];txt(7.2,true,[48,61,45]);d.text(titleLines,x,cy[col]);cy[col]+=titleLines.length*9.2+6;
    for(const b of bullets){cy[col]=drawBullet(b,x+2,cy[col],COL-2,6.8);}cy[col]+=8;
  }
  footer(1);

  d.addPage();await header(2);y=88;
  if(data.targetRoles.length){y=section("TARGET ROLE ALIGNMENT",M,y,CW);let col2=0,ry=[y,y];for(const r of data.targetRoles){const x=xs[col2];const title=[r.company,r.role].filter(Boolean).join(" | ");const titleLines=measureLines(title,COL,7.3,true);const bullets=sentenceBullets(r.alignment);const est=titleLines.length*9.2+bullets.reduce((s,b)=>s+measureLines(b,COL-13,6.75).length*8.7+4,0)+14;if(ry[col2]+est>330&&col2===0)col2=1;if(ry[col2]+est>330)break;txt(7.3,true,sage);d.text(titleLines,x,ry[col2]);ry[col2]+=titleLines.length*9.2+5;for(const b of bullets)ry[col2]=drawBullet(b,x,ry[col2],COL,6.75);ry[col2]+=7;}y=Math.max(...ry)+12;}
  const splitY=Math.max(y,332);let leftY=section("YOUR STRONGEST SELLING POINTS",M,splitY,COL);leftY=drawBullets(data.sellingPoints,M,leftY,COL,540,7.0);
  let rightY=section("THE BIGGEST DIFFERENCE",M+COL+G,splitY,COL);pill("BEFORE",M+COL+G,rightY+8);rightY+=30;rightY=drawParagraph(data.biggestDifferenceBefore,M+COL+G,rightY,COL,6.9,false);rightY+=10;d.setDrawColor(...rule);d.line(M+COL+G,rightY,M+COL+G+COL,rightY);rightY+=18;pill("NOW",M+COL+G,rightY);rightY+=24;rightY=drawParagraph(data.biggestDifferenceNow,M+COL+G,rightY,COL,6.9,true);
  y=Math.max(leftY,rightY,548)+16;y=section("JGO HIRE FINAL ASSESSMENT",M,y,CW);const cardY=y,cardH=Math.max(122,BOTTOM-cardY);
  d.setFillColor(...light);d.roundedRect(M,cardY,CW,cardH,9,9,"F");
  const pairW=(CW-42)/2;const item=(label:string,value:string,x:number,yy:number,w:number)=>{txt(6.1,true,sage);d.text(label.toUpperCase(),x,yy);drawParagraph(value,x,yy+12,w,6.8,true);};
  item("Resume Positioning",data.positioning,M+14,cardY+20,pairW);item("Target Level",data.targetLevel,M+28+pairW,cardY+20,pairW);item("Primary Areas of Alignment",data.primaryAlignment,M+14,cardY+61,pairW);item("Industry Strengths",data.industries,M+28+pairW,cardY+61,pairW);
  if(cardH>116){item("Key Differentiators",data.differentiators,M+14,cardY+102,CW-118);pill((data.status||"READY").toUpperCase(),W-M-84,cardY+111);}
  footer(2);d.save(`${fileBaseName(data.client)}.pdf`);
}

export default function ResumeReadyReportPage(){
  const [report,setReport]=useState<ReportData>(emptyReport),[importText,setImportText]=useState(""),[status,setStatus]=useState("");
  const completion=useMemo(()=>{const c=[report.client,report.transformationBefore,report.transformationAfter,report.changes.length,report.targetRoles.length,report.sellingPoints.length,report.biggestDifferenceBefore,report.biggestDifferenceNow,report.positioning,report.targetLevel,report.primaryAlignment,report.differentiators];return Math.round(c.filter(Boolean).length/c.length*100);},[report]);
  const doImport=()=>{const parsed=parseImport(importText);setReport(parsed);setStatus(parsed.client?`Report parsed for ${parsed.client}. Review below, then download.`:"Report parsed. Add the client name if it was not detected.");};
  const update=(key:keyof ReportData,value:any)=>setReport(r=>({...r,[key]:value}));
  const download=async()=>{try{setStatus("Building clean two-page report...");await makePdf(report);setStatus("Two-page Resume Ready Report downloaded.");}catch(e:any){setStatus(e?.message||"Could not create PDF.");}};
  return <main className="min-h-screen bg-[#f8faf6] px-4 py-7 text-[#344132] md:px-8 md:py-9"><div className="mx-auto max-w-[1320px]">
    <div className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#80907e]">JGO Hire</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Resume Ready Report Builder</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#738071]">Paste one complete ChatGPT report. JGO OS separates the content automatically and turns it into a clean, skimmable two-page client report.</p></div><div className="rounded-2xl border border-[#dfe6dc] bg-white px-5 py-3 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#80907e]">Report readiness</p><div className="mt-2 flex items-center gap-3"><div className="h-2 w-36 overflow-hidden rounded-full bg-[#edf1e9]"><div className="h-full rounded-full bg-[#81987a]" style={{width:`${completion}%`}}/></div><span className="text-sm font-bold text-[#53664f]">{completion}%</span></div></div></div>
    <div className="grid gap-6 xl:grid-cols-[430px_1fr]"><aside className="space-y-5"><section className="rounded-3xl border border-[#dde5d9] bg-white p-5 shadow-[0_12px_35px_rgba(65,83,59,.06)]"><h2 className="text-lg font-bold">Quick Paste</h2><p className="mt-1 text-xs leading-5 text-[#7a8778]">Paste the full JGO OS-ready report from ChatGPT. The PDF measures each wrapped line before placing the next one, so bullets never overlap.</p><textarea value={importText} onChange={e=>setImportText(e.target.value)} rows={22} placeholder="Paste the entire Resume Ready Report here..." className="mt-4 w-full resize-y rounded-2xl border border-[#dce4d8] bg-[#fbfcfa] px-4 py-3 text-sm leading-6 outline-none focus:border-[#aebda8] focus:ring-4 focus:ring-[#dfe8da]/60"/><button onClick={doImport} disabled={!importText.trim()} className="mt-3 w-full rounded-2xl bg-[#53684f] px-4 py-3 text-sm font-bold text-white disabled:opacity-40">Format Report</button>{status&&<p className="mt-3 rounded-xl bg-[#f2f6ef] px-3 py-2 text-xs leading-5 text-[#61705d]">{status}</p>}</section></aside>
      <section><div className="rounded-3xl border border-[#dde5d9] bg-white p-6 shadow-[0_12px_35px_rgba(65,83,59,.06)]"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-bold">Review & Edit</h2><p className="mt-1 text-xs text-[#7a8778]">Content stays detailed here. PDF formatting is handled automatically.</p></div><button onClick={download} disabled={!report.client} className="rounded-2xl bg-[#53684f] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Download 2-Page PDF</button></div>
      <div className="grid gap-4 md:grid-cols-2"><Input label="Client" value={report.client} onChange={v=>update("client",v)}/><Input label="Resume Status" value={report.status} onChange={v=>update("status",v)}/></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Transformation — Before" value={report.transformationBefore} onChange={v=>update("transformationBefore",v)} rows={7}/><Field label="Transformation — After" value={report.transformationAfter} onChange={v=>update("transformationAfter",v)} rows={7}/></div>
      <div className="mt-6"><h3 className="mb-3 text-sm font-bold uppercase tracking-wider text-[#60705d]">What Changed</h3><div className="space-y-4">{report.changes.map((c,i)=><div key={i} className="rounded-2xl border border-[#e0e6dd] bg-[#fbfcfa] p-4"><Input label={`Improvement ${i+1} title`} value={c.title} onChange={v=>{const n=[...report.changes];n[i]={...n[i],title:v};update("changes",n);}}/><div className="mt-3"><Field label="Explanation" value={c.body} onChange={v=>{const n=[...report.changes];n[i]={...n[i],body:v};update("changes",n);}} rows={4}/></div></div>)}</div></div>
      <div className="mt-6"><h3 className="mb-3 text-sm font-bold uppercase tracking-wider text-[#60705d]">Target Role Alignment</h3>{report.targetRoles.map((r,i)=><div key={i} className="mb-4 rounded-2xl border border-[#e0e6dd] bg-[#fbfcfa] p-4"><div className="grid gap-3 md:grid-cols-2"><Input label="Company" value={r.company} onChange={v=>{const n=[...report.targetRoles];n[i]={...n[i],company:v};update("targetRoles",n);}}/><Input label="Role" value={r.role} onChange={v=>{const n=[...report.targetRoles];n[i]={...n[i],role:v};update("targetRoles",n);}}/></div><div className="mt-3"><Field label="Alignment" value={r.alignment} onChange={v=>{const n=[...report.targetRoles];n[i]={...n[i],alignment:v};update("targetRoles",n);}} rows={4}/></div></div>)}</div>
      <div className="mt-6"><Field label="Strongest Selling Points — one per line" value={report.sellingPoints.join("\n")} onChange={v=>update("sellingPoints",splitLines(v))} rows={7}/></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Biggest Difference — Before" value={report.biggestDifferenceBefore} onChange={v=>update("biggestDifferenceBefore",v)}/><Field label="Biggest Difference — Now" value={report.biggestDifferenceNow} onChange={v=>update("biggestDifferenceNow",v)}/><Input label="Resume Positioning" value={report.positioning} onChange={v=>update("positioning",v)}/><Input label="Target Level" value={report.targetLevel} onChange={v=>update("targetLevel",v)}/><Field label="Primary Areas of Alignment" value={report.primaryAlignment} onChange={v=>update("primaryAlignment",v)}/><Field label="Industry Strengths" value={report.industries} onChange={v=>update("industries",v)}/><div className="md:col-span-2"><Field label="Key Differentiators" value={report.differentiators} onChange={v=>update("differentiators",v)}/></div></div>
      </div></section></div></div></main>;
}
