import { createClient } from "@/lib/supabase-server";
import DashboardSchedulePortalClient from "@/components/DashboardSchedulePortalClient";
export const dynamic="force-dynamic";
type RawMeeting={id:number;title:string|null;event_type:string|null;start_at:string;client_id:number|null;intake_call_id:number|null;guest_email:string|null;status:string|null;};
type Meeting={id:number;clientId:number|null;clientName:string;title:string;startAt:string;};
function normalize(v:string|null|undefined){return v?.trim().toLowerCase()??"";}
function isMeeting(e:RawMeeting){const t=normalize(e.event_type),s=normalize(e.status);if(["cancelled","canceled"].includes(s))return false;return ["free 15","free15","coaching session","client session","client_session","appointment"].includes(t);}
function easternWeekStartUtc(now=new Date()){const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit",weekday:"short"}).formatToParts(now);const get=(t:Intl.DateTimeFormatPartTypes)=>parts.find(p=>p.type===t)?.value??"";const y=Number(get("year")),m=Number(get("month")),d=Number(get("day")),w=get("weekday");const idx:Record<string,number>={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};const ed=new Date(Date.UTC(y,m-1,d));ed.setUTCDate(ed.getUTCDate()-(idx[w]??0));const sy=ed.getUTCFullYear(),sm=ed.getUTCMonth()+1,sd=ed.getUTCDate();const on=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",timeZoneName:"shortOffset"}).formatToParts(new Date(Date.UTC(sy,sm-1,sd,12))).find(p=>p.type==="timeZoneName")?.value??"GMT-4";const ma=on.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);const sign=ma?.[1]==="+"?1:-1,h=Number(ma?.[2]??4),mi=Number(ma?.[3]??0);return new Date(Date.UTC(sy,sm-1,sd,0,0)-sign*(h*60+mi)*60000);}
export default async function DashboardScheduleSwap(){const supabase=await createClient(),now=new Date(),nowIso=now.toISOString(),weekStartIso=easternWeekStartUtc(now).toISOString(),futureEnd=new Date(now);futureEnd.setDate(futureEnd.getDate()+120);const{data:events}=await supabase.from("calendar_events").select("id,title,event_type,start_at,client_id,intake_call_id,guest_email,status").not("start_at","is",null).gte("start_at",weekStartIso).lte("start_at",futureEnd.toISOString()).order("start_at",{ascending:true}).limit(200);const filtered=((events??[])as RawMeeting[]).filter(isMeeting);const clientIds=Array.from(new Set(filtered.map(e=>e.client_id).filter((id):id is number=>typeof id==="number")));const leadIds=Array.from(new Set(filtered.map(e=>e.intake_call_id).filter((id):id is number=>typeof id==="number")));const names=new Map<number,string>(),leadNames=new Map<number,string>();if(clientIds.length){const{data}=await supabase.from("clients").select("id,name").in("id",clientIds);for(const c of data??[])names.set(c.id,c.name||"Client");}if(leadIds.length){const{data}=await supabase.from("intake_calls").select("id,name").in("id",leadIds);for(const l of data??[])leadNames.set(l.id,l.name||"Lead");}const meetings:Meeting[]=filtered.map(e=>({id:e.id,clientId:e.client_id,clientName:e.client_id?names.get(e.client_id)||"Client":e.intake_call_id?leadNames.get(e.intake_call_id)||"Lead":e.guest_email||"Calendar meeting",title:e.title||e.event_type||"Meeting",startAt:e.start_at}));const upcoming=meetings.filter(m=>m.startAt>=nowIso),past=meetings.filter(m=>m.startAt>=weekStartIso&&m.startAt<nowIso).sort((a,b)=>b.startAt.localeCompare(a.startAt));return <DashboardSchedulePortalClient upcoming={upcoming} past={past}/>;}
