import Link from "next/link";

type Item={key:string;name:string;detail:string;date:string|null;href:string;minutesUntil:number|null};
function formatTime(value:string|null){if(!value)return"";return new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit",timeZone:"America/New_York"}).format(new Date(value));}
function formatDay(value:string|null){if(!value)return"";return new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric",timeZone:"America/New_York"}).format(new Date(value));}
export default function WeeklySchedule({items}:{items:Item[]}){
 const now=Date.now();const easternNow=new Date(new Date().toLocaleString("en-US",{timeZone:"America/New_York"}));const day=easternNow.getDay();const sunday=new Date(easternNow);sunday.setHours(0,0,0,0);sunday.setDate(easternNow.getDate()-day);const weekStart=sunday.getTime();
 const upcoming=items.filter(i=>i.date&&new Date(i.date).getTime()>=now).sort((a,b)=>(a.date||"").localeCompare(b.date||""));
 const past=items.filter(i=>i.date&&new Date(i.date).getTime()<now&&new Date(i.date).getTime()>=weekStart).sort((a,b)=>(b.date||"").localeCompare(a.date||""));
 const Card=({item,pastItem=false}:{item:Item;pastItem?:boolean})=><Link href={item.href} className={`flex items-center justify-between gap-4 rounded-2xl border px-4 py-4 transition hover:bg-white ${pastItem?"border-[#e7e8e4] bg-[#f6f7f4] opacity-75":"border-[#dce5d7] bg-[#fbfcf9]"}`}><div className="min-w-0"><p className="truncate text-sm font-bold text-[#243128]">{item.name}</p><p className="mt-1 truncate text-xs text-[#708075]">{item.detail}</p></div><div className="shrink-0 text-right"><p className="text-xs font-semibold text-[#5c7454]">{formatDay(item.date)}</p><p className="mt-1 text-xs text-[#7d897f]">{formatTime(item.date)}</p></div></Link>;
 return <section className="rounded-[28px] border border-white/70 bg-white/58 p-6 shadow-[0_22px_60px_rgba(71,91,66,0.12)] backdrop-blur-2xl"><h3 className="text-xl font-bold text-[#243128]">Schedule</h3><p className="mt-1 text-sm text-[#708075]">Upcoming stays on top. Once something passes, it moves into Past This Week until Sunday resets the week.</p><div className="mt-6"><div className="flex items-center justify-between"><h4 className="text-xs font-bold uppercase tracking-[.16em] text-[#647d5b]">Upcoming</h4><span className="rounded-full bg-[#e8eee3] px-2.5 py-1 text-xs font-semibold text-[#5c7454]">{upcoming.length}</span></div><div className="mt-3 space-y-3">{upcoming.length?upcoming.slice(0,6).map(i=><Card key={i.key} item={i}/>):<p className="rounded-2xl border border-dashed p-5 text-sm text-[#708075]">Nothing upcoming right now.</p>}</div></div>{past.length?<div className="mt-7 border-t border-[#e4e9df] pt-6"><div className="flex items-center justify-between"><h4 className="text-xs font-bold uppercase tracking-[.16em] text-[#8b918b]">Past This Week</h4><span className="text-xs text-[#8b918b]">Sunday - today</span></div><div className="mt-3 space-y-3">{past.slice(0,6).map(i=><Card key={i.key} item={i} pastItem/>)}</div></div>:null}</section>;
}
