import Link from "next/link";
import { createClient } from "@/lib/supabase-server";

type Item={key:string;name:string;detail:string;date:string|null;href:string};
function formatTime(value:string|null){if(!value)return"";return new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit",timeZone:"America/New_York"}).format(new Date(value));}
function formatDay(value:string|null){if(!value)return"";return new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric",timeZone:"America/New_York"}).format(new Date(value));}
function normalize(value:string|null|undefined){return value?.trim().toLowerCase()??"";}
export default async function WeeklySchedule(){
 const s=await createClient();const now=new Date();const start=new Date(now);start.setDate(start.getDate()-7);const end=new Date(now);end.setDate(end.getDate()+45);
 const[{data:events},{data:clients}]=await Promise.all([s.from("calendar_events").select("id,title,event_type,start_at,client_id,status,notes").gte("start_at",start.toISOString()).lte("start_at",end.toISOString()).order("start_at",{ascending:true}),s.from("clients").select("id,name")]);
 const names=new Map((clients??[]).map(c=>[c.id,c.name||"Client"]));const items:Item[]=(events??[]).filter(e=>e.start_at&&!['cancelled','canceled'].includes(normalize(e.status))).map(e=>({key:`calendar-${e.id}`,name:e.client_id?names.get(e.client_id)||e.title||"Calendar item":e.title||"Calendar item",detail:e.client_id?`${e.title||e.event_type||"Appointment"}${e.notes?` · ${e.notes}`:""}`:(e.notes||e.event_type||"Calendar item"),date:e.start_at,href:e.client_id?`/clients/${e.client_id}`:`/calendar/${e.id}`}));
 const nowMs=Date.now();const easternNow=new Date(new Date().toLocaleString("en-US",{timeZone:"America/New_York"}));const day=easternNow.getDay();const sunday=new Date(easternNow);sunday.setHours(0,0,0,0);sunday.setDate(easternNow.getDate()-day);const weekStart=sunday.getTime();
 const upcoming=items.filter(i=>i.date&&new Date(i.date).getTime()>=nowMs).sort((a,b)=>(a.date||"").localeCompare(b.date||""));const past=items.filter(i=>i.date&&new Date(i.date).getTime()<nowMs&&new Date(i.date).getTime()>=weekStart).sort((a,b)=>(b.date||"").localeCompare(a.date||""));
 const Card=({item,pastItem=false}:{item:Item;pastItem?:boolean})=><Link href={item.href} className={`flex items-center justify-between gap-4 rounded-2xl border px-4 py-3.5 transition hover:bg-white ${pastItem?"border-[#e7e8e4] bg-[#f6f7f4] opacity-70":"border-[#dce5d7] bg-white/78"}`}><div className="min-w-0"><p className="truncate text-sm font-bold text-[#243128]">{item.name}</p><p className="mt-1 truncate text-xs text-[#708075]">{item.detail}</p></div><div className="shrink-0 text-right"><p className="text-xs font-semibold text-[#5c7454]">{formatDay(item.date)}</p><p className="mt-1 text-xs text-[#7d897f]">{formatTime(item.date)}</p></div></Link>;
 return <section className="mt-5 rounded-[24px] border border-[#dce5d7] bg-[#f8faf6]/90 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#6f8966]">Schedule</p><h3 className="mt-1 text-lg font-bold text-[#243128]">Upcoming + Past This Week</h3><p className="mt-1 text-xs text-[#708075]">Once an appointment passes, it moves below. Past items clear automatically each Sunday.</p></div><Link href="/calendar" className="text-xs font-semibold text-[#647d5b]">View calendar →</Link></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><div className="flex items-center justify-between"><h4 className="text-xs font-bold uppercase tracking-[.14em] text-[#647d5b]">Upcoming</h4><span className="rounded-full bg-[#e8eee3] px-2.5 py-1 text-[11px] font-semibold text-[#5c7454]">{upcoming.length}</span></div><div className="mt-2 space-y-2">{upcoming.length?upcoming.slice(0,4).map(i=><Card key={i.key} item={i}/>):<p className="rounded-2xl border border-dashed p-4 text-xs text-[#708075]">Nothing upcoming.</p>}</div></div><div><div className="flex items-center justify-between"><h4 className="text-xs font-bold uppercase tracking-[.14em] text-[#8b918b]">Past This Week</h4><span className="text-[11px] text-[#8b918b]">Sunday - today</span></div><div className="mt-2 space-y-2">{past.length?past.slice(0,4).map(i=><Card key={i.key} item={i} pastItem/>):<p className="rounded-2xl border border-dashed p-4 text-xs text-[#8b918b]">Nothing has passed yet this week.</p>}</div></div></div></section>;
}
