import Link from "next/link";
import { createClient } from "@/lib/supabase-server";
import { createLeadFromGuideSignup, markGuideSignupContacted } from "./actions";

export const dynamic = "force-dynamic";
type Lead={id:number;first_name:string;email:string;quiz_result_title:string|null;created_at:string;funnel_status:string;contacted_at:string|null;converted_client_id:number|null};
function formatDate(v:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/New_York",timeZoneName:"short"}).format(new Date(v));}
function badge(status:string){if(status==="Converted to Lead")return"bg-[#dfeedd] text-[#3f653c]";if(status==="Contacted")return"bg-[#e9edf5] text-[#53647b]";return"bg-[#f6eedb] text-[#7a6537]";}
export default async function GuideSignupsPage(){
 const supabase=await createClient();
 const{data,error}=await supabase.from("job_search_guide_leads").select("id,first_name,email,quiz_result_title,created_at,funnel_status,contacted_at,converted_client_id").order("created_at",{ascending:false});
 const leads=(data||[]) as Lead[];const newCount=leads.filter(x=>x.funnel_status==="New Signup").length;const contacted=leads.filter(x=>x.funnel_status==="Contacted").length;const converted=leads.filter(x=>x.converted_client_id).length;
 return <main className="min-h-screen bg-[#f8f7f3] p-4 text-[#2f3d32] md:p-8"><div className="mx-auto max-w-7xl">
  <div className="mb-7"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#7b8b78]">Lead Funnel</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#354532]">Survival Guide Signups</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#728075]">Turn free-guide interest into real JGO relationships. Contact them here, then create a full lead profile when the conversation becomes meaningful.</p></div>
  <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Total Signups",leads.length],["New",newCount],["Contacted",contacted],["Converted",converted]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-[#dce5d7] bg-white p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#899588]">{l}</p><p className="mt-1 text-2xl font-bold text-[#4d6247]">{v}</p></div>)}</div>
  {error?<div className="rounded-2xl border bg-white p-5 text-sm">Unable to load signups right now.</div>:leads.length===0?<div className="rounded-2xl border bg-white p-8 text-center">No signups yet.</div>:<div className="space-y-3">{leads.map(lead=><div key={lead.id} className="rounded-2xl border border-[#dfe5dc] bg-white p-5 shadow-sm transition hover:shadow-md"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-lg font-bold text-[#354532]">{lead.first_name}</p><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${badge(lead.funnel_status)}`}>{lead.funnel_status}</span></div><a href={`mailto:${lead.email}`} className="mt-1 block truncate text-sm font-medium text-[#61745c] hover:underline">{lead.email}</a><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-[#818b82]"><span>Job Seeker Survival Guide</span><span>Signed up {formatDate(lead.created_at)}</span>{lead.contacted_at?<span>Contacted {formatDate(lead.contacted_at)}</span>:null}</div>{lead.quiz_result_title&&lead.quiz_result_title!=="Direct Guide Signup"?<p className="mt-2 text-xs text-[#7a877b]">Quiz: {lead.quiz_result_title}</p>:null}</div><div className="flex flex-wrap gap-2 lg:justify-end"><a href={`mailto:${lead.email}?subject=${encodeURIComponent("Checking in from JGO Hire")}`} className="rounded-xl border border-[#cad8c4] px-4 py-2.5 text-xs font-bold text-[#4d6247] hover:bg-[#f2f6ef]">Email</a>{!lead.contacted_at&&!lead.converted_client_id?<form action={markGuideSignupContacted}><input type="hidden" name="signupId" value={lead.id}/><button className="rounded-xl border border-[#cad8c4] px-4 py-2.5 text-xs font-bold text-[#4d6247] hover:bg-[#f2f6ef]">Mark Contacted</button></form>:null}{lead.converted_client_id?<Link href={`/clients/${lead.converted_client_id}`} className="rounded-xl bg-[#647d5b] px-4 py-2.5 text-xs font-bold text-white">View Lead →</Link>:<form action={createLeadFromGuideSignup}><input type="hidden" name="signupId" value={lead.id}/><button className="rounded-xl bg-[#647d5b] px-4 py-2.5 text-xs font-bold text-white hover:bg-[#536b4c]">Create Lead →</button></form>}</div></div></div>)}</div>}
 </div></main>;
}
