"use client";

import { ChangeEvent, useMemo, useState } from "react";

type Experience = { title:string; company:string; location:string; dates:string; bullets:string[] };
type Education = { degree:string; school:string };
type ResumeData = { name:string; contact:string; summary:string; competencies:string[]; experience:Experience[]; education:Education[] };

const emptyResume:ResumeData={name:"",contact:"",summary:"",competencies:[],experience:[],education:[]};
const sectionNames=["PROFESSIONAL SUMMARY","SUMMARY","CORE COMPETENCIES","SKILLS","PROFESSIONAL EXPERIENCE","EXPERIENCE","EDUCATION"];
function isHeading(line:string){return sectionNames.includes(line.trim().toUpperCase())}
function cleanBullet(line:string){return line.replace(/^[•●▪◦\-*]\s*/,"").trim()}
function parseResume(raw:string):ResumeData{
 const lines=raw.replace(/\r/g,"").split("\n").map(x=>x.trim()).filter(Boolean); if(!lines.length)return emptyResume;
 const data:ResumeData={...emptyResume,name:lines[0]||"",contact:lines[1]||"",experience:[],education:[],competencies:[]};
 let section="",i=2;
 while(i<lines.length){const line=lines[i];if(isHeading(line)){section=line.toUpperCase();i++;continue}
  if(section.includes("SUMMARY")){const chunks:string[]=[];while(i<lines.length&&!isHeading(lines[i]))chunks.push(lines[i++]);data.summary=chunks.join(" ");continue}
  if(section.includes("COMPETENC")||section==="SKILLS"){const chunks:string[]=[];while(i<lines.length&&!isHeading(lines[i]))chunks.push(lines[i++]);data.competencies=chunks.join(" • ").split(/\s*[•|]\s*/).map(x=>x.trim()).filter(Boolean);continue}
  if(section.includes("EXPERIENCE")){while(i<lines.length&&!isHeading(lines[i])){const title=lines[i++];if(!title||isHeading(title))break;let company="",location="",dates="";if(i<lines.length&&!lines[i].startsWith("•")&&!isHeading(lines[i])){const parts=lines[i++].split("|").map(x=>x.trim());company=parts[0]||"";if(parts.length>=3){location=parts[1];dates=parts.slice(2).join(" | ")}else if(parts.length===2){dates=parts[1]}}
   const bullets:string[]=[];while(i<lines.length&&!isHeading(lines[i])&&(lines[i].startsWith("•")||lines[i].startsWith("-")||lines[i].startsWith("●"))){bullets.push(cleanBullet(lines[i++]));}
   if(title||company)data.experience.push({title,company,location,dates,bullets});
  }continue}
  if(section==="EDUCATION"){while(i<lines.length&&!isHeading(lines[i])){const degree=lines[i++]||"";const school=i<lines.length&&!isHeading(lines[i])?lines[i++]:"";data.education.push({degree,school})}continue}
  i++;
 }
 return data;
}
function escapeHtml(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]||c))}
export default function ResumeBuilderPage(){
 const[raw,setRaw]=useState("");const[data,setData]=useState<ResumeData>(emptyResume);const[parsed,setParsed]=useState(false);const[error,setError]=useState("");
 const hasResume=useMemo(()=>Boolean(data.name||data.summary||data.experience.length),[data]);
 function parse(){if(!raw.trim()){setError("Paste resume text first.");return}setData(parseResume(raw));setParsed(true);setError("")}
 function handleFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(!/\.(txt|md)$/i.test(file.name)){setError("For this first version, upload a .txt/.md file or paste the resume text. PDF and DOCX auto-reading is the next parser step.");return}const r=new FileReader();r.onload=()=>{const text=String(r.result||"");setRaw(text);setData(parseResume(text));setParsed(true);setError("")};r.readAsText(file)}
 function updateExp(index:number,patch:Partial<Experience>){setData(c=>({...c,experience:c.experience.map((x,i)=>i===index?{...x,...patch}:x)}))}
 function addExp(){setData(c=>({...c,experience:[...c.experience,{title:"",company:"",location:"",dates:"",bullets:[""]}]}))}
 function downloadWord(){const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Georgia,'Times New Roman',serif;color:#000;font-size:10.5pt;line-height:1.22;margin:.55in .65in}h1{text-align:center;font-size:18pt;margin:0 0 2pt;font-weight:700}p.contact{text-align:center;margin:0 0 10pt}h2{font-size:10.5pt;margin:8pt 0 3pt;border-bottom:1px solid #000;padding-bottom:1pt}p{margin:2pt 0}ul{margin:2pt 0 5pt 18pt;padding:0}li{margin:1.5pt 0}.title{font-weight:700}.meta{margin-bottom:3pt}</style></head><body><h1>${escapeHtml(data.name)}</h1><p class="contact">${escapeHtml(data.contact)}</p>${data.summary?`<h2>PROFESSIONAL SUMMARY</h2><p>${escapeHtml(data.summary)}</p>`:""}${data.competencies.length?`<h2>CORE COMPETENCIES</h2><p>${data.competencies.map(escapeHtml).join(" • ")}</p>`:""}<h2>PROFESSIONAL EXPERIENCE</h2>${data.experience.map(x=>`<p class="title">${escapeHtml(x.title)}</p><p class="meta">${escapeHtml([x.company,x.location,x.dates].filter(Boolean).join(" | "))}</p><ul>${x.bullets.filter(Boolean).map(b=>`<li>${escapeHtml(b)}</li>`).join("")}</ul>`).join("")}${data.education.length?`<h2>EDUCATION</h2>${data.education.map(e=>`<p class="title">${escapeHtml(e.degree)}</p><p>${escapeHtml(e.school)}</p>`).join("")}`:""}</body></html>`;const blob=new Blob([html],{type:"application/msword"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${data.name||"JGO Resume"}.doc`;a.click();URL.revokeObjectURL(a.href)}
 return <main className="min-h-screen min-w-0 flex-1 bg-[#f5f7f2] text-[#243128]">
  <header className="border-b border-[#e1e7dd] bg-white px-6 py-7 lg:px-10"><div className="mx-auto max-w-[1500px]"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#7f9975]">JGO Hire</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold">Resume Builder</h1><p className="mt-2 text-sm text-[#708075]">Drop in messy resume content. JGO rebuilds it in your standard format.</p></div>{hasResume&&<div className="flex gap-2"><button onClick={()=>window.print()} className="rounded-xl border border-[#cfd9ca] bg-white px-4 py-2.5 text-sm font-semibold">Download PDF</button><button onClick={downloadWord} className="rounded-xl bg-[#5f7857] px-4 py-2.5 text-sm font-semibold text-white">Download Word</button></div>}</div></div></header>
  <div className="mx-auto grid max-w-[1500px] gap-6 p-6 lg:grid-cols-[minmax(360px,.85fr)_minmax(560px,1.15fr)] lg:p-8">
   <section className="space-y-5 print:hidden">
    <div className="rounded-[24px] border border-[#dfe6da] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#81917d]">Step 1</p><h2 className="mt-1 text-xl font-bold">Add resume</h2></div>{parsed&&<span className="rounded-full bg-[#e4ecdf] px-3 py-1 text-xs font-bold text-[#5f7857]">Parsed</span>}</div><label className="mt-4 block cursor-pointer rounded-2xl border border-dashed border-[#bccbb5] bg-[#f7f9f5] p-4 text-center text-sm font-semibold text-[#597052]">Upload text resume<input type="file" accept=".txt,.md" className="hidden" onChange={handleFile}/></label><div className="my-3 text-center text-[11px] font-bold uppercase tracking-widest text-[#a1aaa0]">or paste</div><textarea value={raw} onChange={e=>setRaw(e.target.value)} rows={12} placeholder="Paste the entire resume here..." className="w-full rounded-2xl border border-[#d8e0d4] p-4 text-sm leading-6 outline-none focus:border-[#8ca282]"/><button onClick={parse} className="mt-3 w-full rounded-xl bg-[#5f7857] px-4 py-3 text-sm font-bold text-white">Auto Format Resume</button>{error&&<p className="mt-3 rounded-xl bg-[#fff3f1] p-3 text-sm text-[#9b554e]">{error}</p>}</div>
    {parsed&&<div className="space-y-4 rounded-[24px] border border-[#dfe6da] bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#81917d]">Step 2 · Review detected fields</p><label className="block text-xs font-bold">Name<input value={data.name} onChange={e=>setData(c=>({...c,name:e.target.value}))} className="mt-1.5 w-full rounded-xl border border-[#d8e0d4] p-3 text-sm"/></label><label className="block text-xs font-bold">Contact line<input value={data.contact} onChange={e=>setData(c=>({...c,contact:e.target.value}))} className="mt-1.5 w-full rounded-xl border border-[#d8e0d4] p-3 text-sm"/></label><label className="block text-xs font-bold">Professional Summary<textarea rows={4} value={data.summary} onChange={e=>setData(c=>({...c,summary:e.target.value}))} className="mt-1.5 w-full rounded-xl border border-[#d8e0d4] p-3 text-sm"/></label><label className="block text-xs font-bold">Core Competencies<textarea rows={3} value={data.competencies.join(" • ")} onChange={e=>setData(c=>({...c,competencies:e.target.value.split("•").map(x=>x.trim()).filter(Boolean)}))} className="mt-1.5 w-full rounded-xl border border-[#d8e0d4] p-3 text-sm"/></label><div><div className="flex items-center justify-between"><p className="text-xs font-bold">Professional Experience</p><button onClick={addExp} className="text-xs font-bold text-[#5f7857]">+ Add role</button></div>{data.experience.map((x,i)=><div key={i} className="mt-3 rounded-2xl bg-[#f7f9f5] p-3"><input value={x.title} onChange={e=>updateExp(i,{title:e.target.value})} placeholder="Job title" className="w-full bg-transparent text-sm font-bold outline-none"/><input value={x.company} onChange={e=>updateExp(i,{company:e.target.value})} placeholder="Company" className="mt-2 w-full rounded-lg border bg-white p-2 text-xs"/><div className="mt-2 grid grid-cols-2 gap-2"><input value={x.location} onChange={e=>updateExp(i,{location:e.target.value})} placeholder="Location" className="rounded-lg border bg-white p-2 text-xs"/><input value={x.dates} onChange={e=>updateExp(i,{dates:e.target.value})} placeholder="Dates" className="rounded-lg border bg-white p-2 text-xs"/></div><textarea rows={4} value={x.bullets.join("\n")} onChange={e=>updateExp(i,{bullets:e.target.value.split("\n")})} placeholder="One bullet per line" className="mt-2 w-full rounded-lg border bg-white p-2 text-xs"/></div>)}</div></div>}
   </section>
   <section className="lg:sticky lg:top-6 lg:self-start"><div className="mb-2 flex items-center justify-between print:hidden"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#81917d]">Live JGO Preview</p><span className="text-xs text-[#89958a]">Template 01</span></div><article id="resume-preview" className="mx-auto min-h-[1056px] w-full max-w-[816px] bg-white px-[52px] py-[46px] font-serif text-[12px] leading-[1.24] text-black shadow-[0_20px_55px_rgba(64,76,59,.13)] print:min-h-0 print:max-w-none print:shadow-none">
    <h1 className="text-center text-[22px] font-bold leading-tight tracking-[.01em]">{data.name||"YOUR NAME"}</h1><p className="mt-1 text-center text-[11px]">{data.contact||"City, State • Phone • Email • LinkedIn"}</p>
    {data.summary&&<ResumeSection title="PROFESSIONAL SUMMARY"><p>{data.summary}</p></ResumeSection>}
    {data.competencies.length>0&&<ResumeSection title="CORE COMPETENCIES"><p>{data.competencies.join(" • ")}</p></ResumeSection>}
    {data.experience.length>0&&<ResumeSection title="PROFESSIONAL EXPERIENCE">{data.experience.map((x,i)=><div key={i} className="mb-2.5"><p className="font-bold">{x.title}</p><p>{[x.company,x.location,x.dates].filter(Boolean).join(" | ")}</p>{x.bullets.some(Boolean)&&<ul className="ml-5 mt-1 list-disc space-y-[2px]">{x.bullets.filter(Boolean).map((b,j)=><li key={j} className="pl-0.5">{b}</li>)}</ul>}</div>)}</ResumeSection>}
    {data.education.length>0&&<ResumeSection title="EDUCATION">{data.education.map((e,i)=><div key={i} className="mb-1"><p className="font-bold">{e.degree}</p><p>{e.school}</p></div>)}</ResumeSection>}
    {!hasResume&&<div className="mt-16 text-center font-sans text-sm text-[#9aa29a]">Your formatted resume will appear here.</div>}
   </article></section>
  </div>
 </main>
}
function ResumeSection({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-[8px]"><h2 className="border-b border-black pb-[1px] text-[12px] font-bold leading-tight">{title}</h2><div className="mt-[3px]">{children}</div></section>}
