"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase-server";

function getClientId(formData: FormData) { const value=Number(formData.get("clientId")); if(!Number.isInteger(value)||value<=0) throw new Error("Invalid client ID."); return value; }
function getServiceId(formData: FormData) { const value=Number(formData.get("serviceId")); if(!Number.isInteger(value)||value<=0) throw new Error("Invalid service ID."); return value; }
async function createTimelineEvent(clientId:number,eventType:string,title:string){ const supabase=await createClient(); const {error}=await supabase.from("client_timeline").upsert({client_id:clientId,event_type:eventType,title,status:"Complete",completed_at:new Date().toISOString()},{onConflict:"client_id,event_type"}); if(error) throw new Error(error.message); }
export async function convertToActiveClient(formData:FormData){const clientId=getClientId(formData);const supabase=await createClient();const{error}=await supabase.from("clients").update({status:"Active"}).eq("id",clientId);if(error)throw new Error(error.message);await createTimelineEvent(clientId,"converted_to_client","Converted to Client");revalidatePath(`/clients/${clientId}`);revalidatePath("/clients");revalidatePath("/");}
export async function revertToLead(formData:FormData){const clientId=getClientId(formData);const supabase=await createClient();const{error}=await supabase.from("clients").update({status:"Lead"}).eq("id",clientId);if(error)throw new Error(error.message);await createTimelineEvent(clientId,"reverted_to_lead","Reverted to Lead");revalidatePath(`/clients/${clientId}`);revalidatePath("/clients");revalidatePath("/");}
export async function archiveClient(formData:FormData){const clientId=getClientId(formData);const supabase=await createClient();const{error}=await supabase.from("clients").update({status:"Archived"}).eq("id",clientId);if(error)throw new Error(error.message);revalidatePath("/clients");revalidatePath("/");redirect("/clients?message=archived");}
export async function restoreClient(formData:FormData){const clientId=getClientId(formData);const supabase=await createClient();const{error}=await supabase.from("clients").update({status:"Active"}).eq("id",clientId);if(error)throw new Error(error.message);revalidatePath(`/clients/${clientId}`);revalidatePath("/");redirect(`/clients/${clientId}`);}
export async function deleteClientPermanently(formData:FormData){const clientId=getClientId(formData);const supabase=await createClient();for(const table of ["calendar_events","follow_ups","tasks","client_notes","payments","client_timeline","client_services"]){const{error}=await supabase.from(table).delete().eq("client_id",clientId);if(error)throw new Error(`Unable to delete related records from ${table}: ${error.message}`);}const{data,error}=await supabase.from("clients").delete().eq("id",clientId).select("id").maybeSingle();if(error)throw new Error(`Unable to delete client: ${error.message}`);if(!data)throw new Error("The client was not deleted. The database did not return a deleted record.");for(const path of ["/","/clients","/revenue","/tasks","/follow-ups","/calendar"]){revalidatePath(path);}redirect("/clients?message=deleted");}
export async function updateServiceStatus(formData:FormData){const clientId=getClientId(formData),serviceId=getServiceId(formData),status=String(formData.get("status")||"");if(!status)throw new Error("Missing status.");const supabase=await createClient();const{error}=await supabase.from("client_services").update({status}).eq("id",serviceId).eq("client_id",clientId);if(error)throw new Error(error.message);revalidatePath(`/clients/${clientId}`);revalidatePath("/");}
export async function markServiceInvoiceSent(formData:FormData){const clientId=getClientId(formData),serviceId=getServiceId(formData),supabase=await createClient();const{error}=await supabase.from("client_services").update({payment_status:"Invoice Sent"}).eq("id",serviceId).eq("client_id",clientId);if(error)throw new Error(error.message);revalidatePath(`/clients/${clientId}`);revalidatePath("/revenue");revalidatePath("/");}
export async function markServicePaid(formData:FormData){const clientId=getClientId(formData),serviceId=getServiceId(formData),supabase=await createClient();const{data:service,error:lookupError}=await supabase.from("client_services").select("price").eq("id",serviceId).eq("client_id",clientId).single();if(lookupError||!service)throw new Error(lookupError?.message||"Service not found.");const{error}=await supabase.from("client_services").update({payment_status:"Paid"}).eq("id",serviceId).eq("client_id",clientId);if(error)throw new Error(error.message);await supabase.from("payments").insert({client_id:clientId,client_service_id:serviceId,amount:Number(service.price??0),payment_date:new Date().toISOString().slice(0,10),payment_status:"Paid",payment_method:null,notes:"Marked paid from client profile."});revalidatePath(`/clients/${clientId}`);revalidatePath("/");}
export async function deleteService(formData:FormData){const clientId=getClientId(formData),serviceId=getServiceId(formData),supabase=await createClient();const{error}=await supabase.from("client_services").delete().eq("id",serviceId).eq("client_id",clientId);if(error)throw new Error(error.message);const{count}=await supabase.from("client_services").select("id",{count:"exact",head:true}).eq("client_id",clientId);if(!count)await supabase.from("client_timeline").delete().eq("client_id",clientId).eq("event_type","services_selected");revalidatePath(`/clients/${clientId}`);revalidatePath("/");}
export async function updateService(formData:FormData){const clientId=getClientId(formData),serviceId=getServiceId(formData);const price=formData.get("price"),dateAdded=String(formData.get("dateAdded")||""),scheduledDate=String(formData.get("scheduledDate")||""),notes=String(formData.get("notes")||"").trim(),supabase=await createClient();const{error}=await supabase.from("client_services").update({price:price?Number(price):null,date_added:dateAdded||null,scheduled_date:scheduledDate||null,notes:notes||null}).eq("id",serviceId).eq("client_id",clientId);if(error)throw new Error(error.message);revalidatePath(`/clients/${clientId}`);revalidatePath("/");}
export async function toggleTimelineStep(formData:FormData){const clientId=getClientId(formData),eventType=String(formData.get("eventType")||""),title=String(formData.get("title")||"");if(!eventType)throw new Error("Missing timeline event.");const supabase=await createClient();const{data:existing,error}=await supabase.from("client_timeline").select("id").eq("client_id",clientId).eq("event_type",eventType);if(error)throw new Error(error.message);if(existing?.length){const{error:e}=await supabase.from("client_timeline").delete().eq("client_id",clientId).eq("event_type",eventType);if(e)throw new Error(e.message);}else{const{error:e}=await supabase.from("client_timeline").insert({client_id:clientId,event_type:eventType,title,status:"Complete",completed_at:new Date().toISOString()});if(e)throw new Error(e.message);}revalidatePath(`/clients/${clientId}`);}
export async function addClientNote(formData:FormData){const clientId=getClientId(formData),noteDate=String(formData.get("noteDate")||""),content=String(formData.get("content")||"").trim();if(!content)throw new Error("Note cannot be empty.");const supabase=await createClient();const{error}=await supabase.from("client_notes").insert({client_id:clientId,note_date:noteDate||new Date().toISOString().slice(0,10),content});if(error)throw new Error(error.message);revalidatePath(`/clients/${clientId}`);}
export async function deleteClientNote(formData:FormData){const clientId=getClientId(formData),noteId=Number(formData.get("noteId"));if(!Number.isInteger(noteId)||noteId<=0)throw new Error("Invalid note ID.");const supabase=await createClient();const{error}=await supabase.from("client_notes").delete().eq("id",noteId).eq("client_id",clientId);if(error)throw new Error(error.message);revalidatePath(`/clients/${clientId}`);}
function easternOffsetForLocal(date:string,time:string){const probe=new Date(`${date}T${time}:00Z`);const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",timeZoneName:"shortOffset",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(probe);const label=parts.find(p=>p.type==="timeZoneName")?.value||"GMT-5";const m=label.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);if(!m)return "-05:00";return `${m[1]}${m[2].padStart(2,"0")}:${(m[3]||"00").padStart(2,"0")}`;}
function easternIso(date:string,time:string){return new Date(`${date}T${time}:00${easternOffsetForLocal(date,time)}`).toISOString();}
export async function addCalendarEvent(formData:FormData){const clientId=getClientId(formData),eventType=String(formData.get("eventType")||""),eventDate=String(formData.get("eventDate")||""),eventTime=String(formData.get("eventTime")||""),notes=String(formData.get("notes")||"").trim();if(!eventType||!eventDate)throw new Error("Missing event type or date.");const supabase=await createClient(),isInterview=eventType==="Client Interview",startTime=eventTime||"09:00",startAt=easternIso(eventDate,startTime),endAt=new Date(new Date(startAt).getTime()+3600000).toISOString();const{error}=await supabase.from("calendar_events").insert({client_id:clientId,event_type:isInterview?"interview":eventType,title:eventType,start_at:startAt,end_at:endAt,notes:notes||null});if(error)throw new Error(error.message);if(eventType==="Free 15")await createTimelineEvent(clientId,"free15_scheduled","Free 15 Scheduled");revalidatePath(`/clients/${clientId}`);revalidatePath("/calendar");revalidatePath("/");}
export async function deleteCalendarEvent(formData:FormData){const clientId=getClientId(formData),eventId=Number(formData.get("eventId"));if(!Number.isInteger(eventId)||eventId<=0)throw new Error("Invalid event ID.");const supabase=await createClient();const{error}=await supabase.from("calendar_events").delete().eq("id",eventId).eq("client_id",clientId);if(error)throw new Error(error.message);revalidatePath(`/clients/${clientId}`);revalidatePath("/calendar");revalidatePath("/");}
