"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

type Note={id:number;note_date:string|null;content:string};

function inline(text:string){const parts=text.split(/(\*\*[^*]+\*\*|\*[^*]+\*)/g);return parts.filter(Boolean).map((part,i)=>{if(part.startsWith("**")&&part.endsWith("**"))return <strong key={i}>{part.slice(2,-2)}</strong>;if(part.startsWith("*")&&part.endsWith("*"))return <em key={i}>{part.slice(1,-1)}</em>;return <span key={i}>{part}</span>})}
function NoteBody({content}:{content:string}){const lines=content.split("\n");return <div className="space-y-1 text-sm leading-6 text-[#344239]">{lines.map((line,i)=>{const trimmed=line.trim();if(/^[-•]\s+/.test(trimmed))return <div key={i} className="flex gap-2 pl-2"><span>•</span><span>{inline(trimmed.replace(/^[-•]\s+/,""))}</span></div>;if(/^\d+\.\s+/.test(trimmed))return <div key={i} className="flex gap-2 pl-2"><span>{trimmed.match(/^\d+\./)?.[0]}</span><span>{inline(trimmed.replace(/^\d+\.\s+/,""))}</span></div>;return trimmed?<p key={i}>{inline(line)}</p>:<div key={i} className="h-2"/>})}</div>}
function htmlToMarkdown(root:HTMLElement){function walk(node:Node):string{if(node.nodeType===Node.TEXT_NODE)return node.textContent||"";if(!(node instanceof HTMLElement))return"";const inner=Array.from(node.childNodes).map(walk).join("");const tag=node.tagName.toLowerCase();if(tag==="strong"||tag==="b")return`**${inner}**`;if(tag==="em"||tag==="i")return`*${inner}*`;if(tag==="br")return"\n";if(tag==="li")return`- ${inner.trim()}\n`;if(tag==="p"||tag==="div")return`${inner.trim()}\n`;if(tag==="ul"||tag==="ol")return inner;return inner}return Array.from(root.childNodes).map(walk).join("").replace(/\n{3,}/g,"\n\n").trim()}

export default function ClientNotes({clientId,notes}:{clientId:number;notes:Note[]}){const router=useRouter();const editor=useRef<HTMLDivElement>(null);const[open,setOpen]=useState(false);const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[editing,setEditing]=useState<Note|null>(null);const[saving,setSaving]=useState(false);function command(cmd:string){editor.current?.focus();document.execCommand(cmd,false)}function reset(){setOpen(false);setEditing(null);if(editor.current)editor.current.innerHTML=""}function startEdit(note:Note){setEditing(note);setDate(note.note_date||new Date().toISOString().slice(0,10));setOpen(true);setTimeout(()=>{if(editor.current)editor.current.innerText=note.content},0)}async function save(){const content=editor.current?htmlToMarkdown(editor.current):"";if(!content.trim())return;setSaving(true);if(editing)await supabase.from("client_notes").update({note_date:date,content}).eq("id",editing.id).eq("client_id",clientId);else await supabase.from("client_notes").insert({client_id:clientId,note_date:date,content});setSaving(false);reset();router.refresh()}async function remove(id:number){if(!confirm("Delete this note?"))return;await supabase.from("client_notes").delete().eq("id",id).eq("client_id",clientId);router.refresh()}
return <section className="rounded-2xl border border-[#dfe6db] bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold text-[#243128]">Notes</h2><p className="mt-1 text-sm text-[#708075]">Keep call notes and client context here. Formatting is preserved.</p></div><button type="button" onClick={()=>{setOpen(true);setEditing(null);setDate(new Date().toISOString().slice(0,10));setTimeout(()=>editor.current?.focus(),0)}} className="rounded-xl bg-[#647d5b] px-4 py-2.5 text-sm font-semibold text-white">+ Add Note</button></div>{open?<div className="mt-5 rounded-2xl border border-[#d7e1d0] bg-[#fbfcf9] p-4"><div className="flex flex-wrap items-center gap-2"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-lg border border-[#d7e1d0] bg-white px-3 py-2 text-sm"/><button type="button" onClick={()=>command("bold")} className="h-9 min-w-9 rounded-lg border bg-white px-3 font-bold">B</button><button type="button" onClick={()=>command("italic")} className="h-9 min-w-9 rounded-lg border bg-white px-3 italic">I</button><button type="button" onClick={()=>command("insertUnorderedList")} className="h-9 rounded-lg border bg-white px-3 text-sm font-semibold">• List</button></div><div ref={editor} contentEditable suppressContentEditableWarning className="mt-3 min-h-[150px] max-h-[360px] overflow-y-auto rounded-xl border border-[#d7e1d0] bg-white px-4 py-3 text-sm leading-6 outline-none focus:border-[#9fb294]" data-placeholder="Paste or type notes here..."/><div className="mt-3 flex gap-2"><button type="button" onClick={save} disabled={saving} className="rounded-xl bg-[#647d5b] px-4 py-2 text-sm font-semibold text-white">{saving?"Saving...":editing?"Save Changes":"Save Note"}</button><button type="button" onClick={reset} className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold text-[#647066]">Cancel</button></div></div>:null}<div className="mt-5 space-y-3">{notes.length?notes.map(n=><article key={n.id} className="rounded-xl border border-[#e4e9df] bg-[#fbfcf9] p-4"><div className="mb-3 flex items-center justify-between gap-3"><span className="text-xs font-semibold text-[#708075]">{n.note_date}</span><div className="flex gap-3"><button type="button" onClick={()=>startEdit(n)} className="text-xs font-semibold text-[#647d5b]">Edit</button><button type="button" onClick={()=>remove(n.id)} className="text-xs font-semibold text-[#9a554d]">Delete</button></div></div><NoteBody content={n.content}/></article>):<p className="rounded-xl border border-dashed p-5 text-sm text-[#708075]">No notes yet.</p>}</div></section>}
