"use client";
import {useRouter} from "next/navigation";import{useState}from"react";import{createClient}from"@/lib/supabase-browser";
type Props={file:{id:number;file_name:string;file_path:string;file_type:string|null;file_size:number|null;visible_in_portal?:boolean}};
function size(b:number|null){if(!b||b<=0)return"Unknown size";if(b<1024)return`${b} B`;const k=b/1024;if(k<1024)return`${k.toFixed(k>=100?0:1)} KB`;const m=k/1024;return`${m.toFixed(m>=100?0:1)} MB`}
function details(t:string|null,n:string){const x=t?.toLowerCase()??"",e=n.split(".").pop()?.toLowerCase()??"";if(x.includes("pdf")||e==="pdf")return{label:"PDF",icon:"▤",c:"bg-[#f7e9e6] text-[#9a554d]"};if(x.includes("word")||x.includes("document")||["doc","docx"].includes(e))return{label:"Word document",icon:"▤",c:"bg-[#e7edf4] text-[#52697b]"};if(x.includes("image")||["jpg","jpeg","png","gif","webp"].includes(e))return{label:"Image",icon:"▧",c:"bg-[#eee8f3] text-[#6d5878]"};return{label:e?`${e.toUpperCase()} file`:"Document",icon:"▤",c:"bg-[#edf2e9] text-[#647d5b]"}}
export default function FileRow({file}:Props){const router=useRouter(),[down,setDown]=useState(false),[del,setDel]=useState(false),[sharing,setSharing]=useState(false),[shared,setShared]=useState(Boolean(file.visible_in_portal)),[err,setErr]=useState("");const d=details(file.file_type,file.file_name);
async function toggleShare(){setSharing(true);setErr("");try{const s=createClient(),next=!shared;const{error}=await s.from("client_files").update({visible_in_portal:next}).eq("id",file.id);if(error)throw new Error(error.message);setShared(next);router.refresh()}catch(e){setErr(e instanceof Error?e.message:"Could not update portal sharing.")}finally{setSharing(false)}}
async function download(){setDown(true);setErr("");try{const s=createClient();const{data,error}=await s.storage.from("client-files").createSignedUrl(file.file_path,60);if(error)throw new Error(error.message);if(!data?.signedUrl)throw new Error("Secure link unavailable.");window.open(data.signedUrl,"_blank","noopener,noreferrer")}catch(e){setErr(e instanceof Error?e.message:"Could not download file.")}finally{setDown(false)}}
async function remove(){if(!window.confirm(`Delete "${file.file_name}" permanently?`))return;setDel(true);setErr("");try{const s=createClient();const{error:se}=await s.storage.from("client-files").remove([file.file_path]);if(se)throw new Error(se.message);const{error}=await s.from("client_files").delete().eq("id",file.id);if(error)throw new Error(error.message);router.refresh()}catch(e){setErr(e instanceof Error?e.message:"Could not delete file.")}finally{setDel(false)}}
return <div className="group px-5 py-4 transition hover:bg-[#fafbf8]"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-4"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-lg font-semibold ${d.c}`}>{d.icon}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-semibold text-[#344331]">{file.file_name}</p>{shared?<span className="rounded-full bg-[#e8eee3] px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-[#4d6247]">Shared in Portal</span>:null}</div><div className="mt-1 flex gap-2 text-xs text-[#849080]"><span>{d.label}</span><span>•</span><span>{size(file.file_size)}</span></div></div></div><div className="flex flex-wrap items-center gap-2 pl-[60px] sm:pl-0"><button onClick={toggleShare} disabled={sharing||del} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${shared?"border-[#c8d8c1] bg-[#eef4ea] text-[#4d6247]":"border-[#d7e1d0] bg-white text-[#4d6247]"}`}>{sharing?"Saving...":shared?"Remove from Portal":"Share in Client Portal"}</button><button onClick={download} disabled={down||del} className="rounded-lg border border-[#d7e1d0] bg-white px-3 py-2 text-xs font-semibold text-[#4d6247]">{down?"Preparing...":"Download"}</button><button onClick={remove} disabled={down||del} className="rounded-lg border border-[#ead4d0] bg-white px-3 py-2 text-xs font-semibold text-[#a45f58]">{del?"Deleting...":"Delete"}</button></div></div>{err?<div className="mt-3 rounded-xl bg-[#fbefed] px-4 py-3 text-sm font-semibold text-[#9a554d]">{err}</div>:null}</div>}
